/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Builder, Parser } from 'xml2js';

export function xmlSerialize(rootName: string, value: unknown): string {
  const builder = new Builder();
  return builder.buildObject({ [rootName]: value });
}

export async function xmlDeserialize(
  rootName: string,
  xmlString: string
): Promise<any> {
  const parser = new Parser({ rootName, explicitArray: false });
  return (await parser.parseStringPromise(xmlString))[rootName];
}
