/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface A2pClass {
  messageClass?: string;
  classDescription?: string;
}

export const a2pClassSchema: Schema<A2pClass> = object({
  messageClass: [
    'messageClass',
    optional(string()),
    { xmlName: 'MessageClass' },
  ],
  classDescription: [
    'classDescription',
    optional(string()),
    { xmlName: 'ClassDescription' },
  ],
});
