/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface A2pCampaignId {
  campaignId?: string;
  description?: string;
  accountId?: string;
}

export const a2pCampaignIdSchema: Schema<A2pCampaignId> = object({
  campaignId: ['campaignId', optional(string()), { xmlName: 'CampaignId' }],
  description: [
    'description',
    optional(string()),
    { xmlName: 'CampaignIdDescription' },
  ],
  accountId: ['accountId', optional(string()), { xmlName: 'AccountId' }],
});
