/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for A2pLongCodeEnum
 */
export enum A2pLongCodeEnum {
  ON = 'ON',
  OFF = 'OFF',
  DEFAULTON = 'DEFAULT_ON',
  DEFAULTOFF = 'DEFAULT_OFF',
  INCORRECTVALUE = 'INCORRECT_VALUE',
}

/**
 * Schema for A2pLongCodeEnum
 */
export const a2pLongCodeEnumSchema: Schema<A2pLongCodeEnum> = stringEnum(A2pLongCodeEnum);
