/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for A2pStateEnum
 */
export enum A2pStateEnum {
  OFF = 'OFF',
  SYSTEMDEFAULT = 'SYSTEM_DEFAULT',
  OVERRIDDEN = 'OVERRIDDEN',
}

/**
 * Schema for A2pStateEnum
 */
export const a2pStateEnumSchema: Schema<A2pStateEnum> = stringEnum(A2pStateEnum);
