/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Action1Enum, action1EnumSchema } from './action1Enum';

export interface A2pSettings {
  messageClass?: string;
  campaignId?: string;
  action?: Action1Enum;
}

export const a2pSettingsSchema: Schema<A2pSettings> = object({
  messageClass: [
    'messageClass',
    optional(string()),
    { xmlName: 'MessageClass' },
  ],
  campaignId: ['campaignId', optional(string()), { xmlName: 'CampaignId' }],
  action: ['action', optional(action1EnumSchema), { xmlName: 'Action' }],
});
