/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface AccessRestriction {
  product?: string;
  accessRestrictionTypes?: string[];
}

export const accessRestrictionSchema: Schema<AccessRestriction> = object({
  product: ['product', optional(string()), { xmlName: 'RestrictedProduct' }],
  accessRestrictionTypes: [
    'accessRestrictionTypes',
    optional(array(string(), { xmlItemName: 'RestrictedAccessType' })),
    { xmlName: 'RestrictedAccessTypes' },
  ],
});
