/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { SipAuthSettings, sipAuthSettingsSchema } from './sipAuthSettings';

export interface AccountSipAuthSettingsResponse {
  payload?: SipAuthSettings;
}

export const accountSipAuthSettingsResponseSchema: Schema<AccountSipAuthSettingsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipAuthSettingsSchema)),
      { xmlName: 'SipAuthentication' },
    ],
  }
);
