/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AccountProduct, accountProductSchema } from './accountProduct';

export interface AccountProductResponse {
  payload?: AccountProduct;
}

export const accountProductResponseSchema: Schema<AccountProductResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => accountProductSchema)),
      { xmlName: 'Product' },
    ],
  }
);
