/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { AccountPayload, accountPayloadSchema } from './accountPayload';

export interface AccountPayloads {
  accounts?: AccountPayload[];
}

export const accountPayloadsSchema: Schema<AccountPayloads> = object({
  accounts: [
    'accounts',
    optional(array(lazy(() => accountPayloadSchema))),
    { xmlName: 'Account' },
  ],
});
