/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema';

export interface AccountSmsFeatureSettings {
  zone1?: boolean;
  zone2?: boolean;
  zone3?: boolean;
  zone4?: boolean;
  zone5?: boolean;
  smppEnabled?: boolean;
  defaultProvider?: number;
}

export const accountSmsFeatureSettingsSchema: Schema<AccountSmsFeatureSettings> = object(
  {
    zone1: ['zone1', optional(boolean()), { xmlName: 'Zone1' }],
    zone2: ['zone2', optional(boolean()), { xmlName: 'Zone2' }],
    zone3: ['zone3', optional(boolean()), { xmlName: 'Zone3' }],
    zone4: ['zone4', optional(boolean()), { xmlName: 'Zone4' }],
    zone5: ['zone5', optional(boolean()), { xmlName: 'Zone5' }],
    smppEnabled: [
      'smppEnabled',
      optional(boolean()),
      { xmlName: 'SmppEnabled' },
    ],
    defaultProvider: [
      'defaultProvider',
      optional(number()),
      { xmlName: 'DefaultProvider' },
    ],
  }
);
