/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { SiteHost, siteHostSchema } from './siteHost';

export interface AccountSitesHosts {
  siteHosts?: SiteHost[];
}

export const accountSitesHostsSchema: Schema<AccountSitesHosts> = object({
  siteHosts: [
    'siteHosts',
    optional(array(lazy(() => siteHostSchema))),
    { xmlName: 'SiteHost' },
  ],
});
