/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { AccountProduct, accountProductSchema } from './accountProduct';

export interface AccountProducts {
  accountProducts?: AccountProduct[];
}

export const accountProductsSchema: Schema<AccountProducts> = object({
  accountProducts: [
    'accountProducts',
    optional(array(lazy(() => accountProductSchema))),
    { xmlName: 'Product' },
  ],
});
