/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountSmsFeature,
  accountSmsFeatureSchema,
} from './accountSmsFeature';

export interface AccountSmsFeatureResponse {
  payload?: AccountSmsFeature;
}

export const accountSmsFeatureResponseSchema: Schema<AccountSmsFeatureResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => accountSmsFeatureSchema)),
      { xmlName: 'AccountSmsFeature' },
    ],
  }
);
