/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountHttpFeature,
  accountHttpFeatureSchema,
} from './accountHttpFeature';

export interface AccountHttpFeatureResponse {
  payload?: AccountHttpFeature;
}

export const accountHttpFeatureResponseSchema: Schema<AccountHttpFeatureResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => accountHttpFeatureSchema)),
      { xmlName: 'AccountHttpFeature' },
    ],
  }
);
