/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { SipCredential, sipCredentialSchema } from './sipCredential';

export interface AccountSipCredentials {
  accountId?: number;
  sipCredentials?: SipCredential[];
}

export const accountSipCredentialsSchema: Schema<AccountSipCredentials> = object(
  {
    accountId: ['accountId', optional(number()), { xmlName: 'Account' }],
    sipCredentials: [
      'sipCredentials',
      optional(array(lazy(() => sipCredentialSchema))),
      { xmlName: 'SipCredential' },
    ],
  }
);
