/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AccountProducts, accountProductsSchema } from './accountProducts';

export interface AccountProductsResponse {
  payload?: AccountProducts;
}

export const accountProductsResponseSchema: Schema<AccountProductsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => accountProductsSchema)),
      { xmlName: 'Products' },
    ],
  }
);
