/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  AccountSipCredentials,
  accountSipCredentialsSchema,
} from './accountSipCredentials';
import {
  SipCredentialError,
  sipCredentialErrorSchema,
} from './sipCredentialError';

export interface AccountSipCredentialsCreateResponse {
  payload?: AccountSipCredentials;
  errors?: SipCredentialError[];
}

export const accountSipCredentialsCreateResponseSchema: Schema<AccountSipCredentialsCreateResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => accountSipCredentialsSchema)),
      { xmlName: 'ValidSipCredentials' },
    ],
    errors: [
      'errors',
      optional(
        array(lazy(() => sipCredentialErrorSchema), { xmlItemName: 'Error' })
      ),
      { xmlName: 'Errors' },
    ],
  }
);
