/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountMmsFeatureSettings,
  accountMmsFeatureSettingsSchema,
} from './accountMmsFeatureSettings';

export interface AccountMmsFeatureSettingsResponse {
  payload?: AccountMmsFeatureSettings;
}

export const accountMmsFeatureSettingsResponseSchema: Schema<AccountMmsFeatureSettingsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => accountMmsFeatureSettingsSchema)),
      { xmlName: 'mmsSettings' },
    ],
  }
);
