/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountMmsFeature,
  accountMmsFeatureSchema,
} from './accountMmsFeature';

export interface AccountMmsFeatureResponse {
  payload?: AccountMmsFeature;
}

export const accountMmsFeatureResponseSchema: Schema<AccountMmsFeatureResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => accountMmsFeatureSchema)),
      { xmlName: 'MmsFeature' },
    ],
  }
);
