/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountMmsFeatureSettings,
  accountMmsFeatureSettingsSchema,
} from './accountMmsFeatureSettings';
import { Mm4Settings, mm4SettingsSchema } from './mm4Settings';

export interface AccountMmsFeature {
  mmsFeatureSettings?: AccountMmsFeatureSettings;
  mm4Settings?: Mm4Settings;
}

export const accountMmsFeatureSchema: Schema<AccountMmsFeature> = object({
  mmsFeatureSettings: [
    'mmsFeatureSettings',
    optional(lazy(() => accountMmsFeatureSettingsSchema)),
    { xmlName: 'MmsSettings' },
  ],
  mm4Settings: [
    'mm4Settings',
    optional(lazy(() => mm4SettingsSchema)),
    { xmlName: 'MM4Settings' },
  ],
});
