/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ActionEnum
 */
export enum ActionEnum {
  UNCHANGED = 'UNCHANGED',
  OFF = 'OFF',
  ASSPECIFIED = 'AS_SPECIFIED',
  INCORRECTVALUE = 'INCORRECT_VALUE',
}

/**
 * Schema for ActionEnum
 */
export const actionEnumSchema: Schema<ActionEnum> = stringEnum(ActionEnum);
