/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Action1Enum
 */
export enum Action1Enum {
  UNCHANGED = 'UNCHANGED',
  SYSTEMDEFAULT = 'SYSTEM_DEFAULT',
  OFF = 'OFF',
  ASSPECIFIED = 'AS_SPECIFIED',
  INCORRECTVALUE = 'INCORRECT_VALUE',
}

/**
 * Schema for Action1Enum
 */
export const action1EnumSchema: Schema<Action1Enum> = stringEnum(Action1Enum);
