/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  E911GeocodeAddress,
  e911GeocodeAddressSchema,
} from './e911GeocodeAddress';

export interface AddressErrorDescription {
  addressInconsistencies?: string;
  recommendedAddress?: E911GeocodeAddress;
}

export const addressErrorDescriptionSchema: Schema<AddressErrorDescription> = object(
  {
    addressInconsistencies: [
      'addressInconsistencies',
      optional(string()),
      { xmlName: 'AddressInconsistencies' },
    ],
    recommendedAddress: [
      'recommendedAddress',
      optional(lazy(() => e911GeocodeAddressSchema)),
      { xmlName: 'RecommendedAddress' },
    ],
  }
);
