/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AddressTypeEnum
 */
export enum AddressTypeEnum {
  SERVICE = 'SERVICE',
  BILLING = 'BILLING',
  DLDA = 'DLDA',
  E911 = 'E911',
}

/**
 * Schema for AddressTypeEnum
 */
export const addressTypeEnumSchema: Schema<AddressTypeEnum> = stringEnum(AddressTypeEnum);
