/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema';
import { AddressesPayload, addressesPayloadSchema } from './addressesPayload';
import { PaginationLinks, paginationLinksSchema } from './paginationLinks';

export interface AddressesResponse {
  payload?: AddressesPayload;
  paginationLinks?: PaginationLinks;
  totalCount?: number;
}

export const addressesResponseSchema: Schema<AddressesResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => addressesPayloadSchema)),
    { xmlName: 'Addresses' },
  ],
  paginationLinks: [
    'paginationLinks',
    optional(lazy(() => paginationLinksSchema)),
    { xmlName: 'Links' },
  ],
  totalCount: ['totalCount', optional(number()), { xmlName: 'TotalCount' }],
});
