/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { E911Address, e911AddressSchema } from './e911Address';

export interface AddressesPayload {
  addresses?: E911Address[];
  totalCount?: number;
}

export const addressesPayloadSchema: Schema<AddressesPayload> = object({
  addresses: [
    'addresses',
    optional(array(lazy(() => e911AddressSchema))),
    { xmlName: 'Address' },
  ],
  totalCount: ['totalCount', optional(number()), { xmlName: 'TotalCount' }],
});
