/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AdminParametersPayload {
  activityState?: string;
  bandwidthPrime?: string;
}

export const adminParametersPayloadSchema: Schema<AdminParametersPayload> = object(
  {
    activityState: [
      'activityState',
      optional(string()),
      { xmlName: 'ActivityState' },
    ],
    bandwidthPrime: [
      'bandwidthPrime',
      optional(string()),
      { xmlName: 'BandwidthPrime' },
    ],
  }
);
