/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AdminParametersPayload,
  adminParametersPayloadSchema,
} from './adminParametersPayload';

export interface AdminParametersResponse {
  payload?: AdminParametersPayload;
}

export const adminParametersResponseSchema: Schema<AdminParametersResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => adminParametersPayloadSchema)),
      { xmlName: 'AdminParameters' },
    ],
  }
);
