/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface AllInternationalNumbers {
  allShortCode?: boolean;
  anyNanp?: boolean;
  anyShortCode?: boolean;
  allNanp?: boolean;
  allInternational?: boolean;
  anyInternational?: boolean;
  empty?: boolean;
}

export const allInternationalNumbersSchema: Schema<AllInternationalNumbers> = object(
  {
    allShortCode: ['allShortCode', optional(boolean())],
    anyNanp: ['anyNanp', optional(boolean())],
    anyShortCode: ['anyShortCode', optional(boolean())],
    allNanp: ['allNanp', optional(boolean())],
    allInternational: ['allInternational', optional(boolean())],
    anyInternational: ['anyInternational', optional(boolean())],
    empty: ['empty', optional(boolean())],
  }
);
