/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import {
  AlternateEndUserIdentifierE911Status,
  alternateEndUserIdentifierE911StatusSchema,
} from './alternateEndUserIdentifierE911Status';
import {
  EmergencyNotificationGroupPayload,
  emergencyNotificationGroupPayloadSchema,
} from './emergencyNotificationGroupPayload';
import {
  PreferredLanguageEnum,
  preferredLanguageEnumSchema,
} from './preferredLanguageEnum';

export interface AlternateEndUserIdentifier {
  identifier?: string;
  callbackNumber?: string;
  pidfloEnabled?: boolean;
  callerName?: string;
  preferredLanguage?: PreferredLanguageEnum;
  locationId?: string;
  groupPayload?: EmergencyNotificationGroupPayload;
  e911Status?: AlternateEndUserIdentifierE911Status;
}

export const alternateEndUserIdentifierSchema: Schema<AlternateEndUserIdentifier> = object(
  {
    identifier: ['identifier', optional(string()), { xmlName: 'Identifier' }],
    callbackNumber: [
      'callbackNumber',
      optional(string()),
      { xmlName: 'CallbackNumber' },
    ],
    pidfloEnabled: [
      'pidfloEnabled',
      optional(boolean()),
      { xmlName: 'PIDFLOEnabled' },
    ],
    callerName: ['callerName', optional(string()), { xmlName: 'CallerName' }],
    preferredLanguage: [
      'preferredLanguage',
      optional(preferredLanguageEnumSchema),
      { xmlName: 'PreferredLanguage' },
    ],
    locationId: ['locationId', optional(string()), { xmlName: 'LocationId' }],
    groupPayload: [
      'groupPayload',
      optional(lazy(() => emergencyNotificationGroupPayloadSchema)),
      { xmlName: 'EmergencyNotificationGroup' },
    ],
    e911Status: [
      'e911Status',
      optional(lazy(() => alternateEndUserIdentifierE911StatusSchema)),
      { xmlName: 'E911' },
    ],
  }
);
