/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  AlternateEndUserIdentifier,
  alternateEndUserIdentifierSchema,
} from './alternateEndUserIdentifier';

export interface AlternateEndUserIdentifiers {
  identifiers?: AlternateEndUserIdentifier[];
}

export const alternateEndUserIdentifiersSchema: Schema<AlternateEndUserIdentifiers> = object(
  {
    identifiers: [
      'identifiers',
      optional(array(lazy(() => alternateEndUserIdentifierSchema))),
      { xmlName: 'AlternateEndUserIdentifier' },
    ],
  }
);
