/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, unknown } from '../schema';
import { ValidationError, validationErrorSchema } from './validationError';

export interface AnalyticsResponse {
  payload?: unknown;
  errors?: ValidationError[];
}

export const analyticsResponseSchema: Schema<AnalyticsResponse> = object({
  payload: ['payload', optional(unknown())],
  errors: [
    'errors',
    optional(
      array(
        lazy(() => validationErrorSchema),
        { xmlItemName: 'ValidationError' }
      )
    ),
    { xmlName: 'ErrorList' },
  ],
});
