/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  AssociatedSipPeer,
  associatedSipPeerSchema,
} from './associatedSipPeer';

export interface AssociatedSipPeers {
  associatedSipPeers?: AssociatedSipPeer[];
}

export const associatedSipPeersSchema: Schema<AssociatedSipPeers> = object({
  associatedSipPeers: [
    'associatedSipPeers',
    optional(array(lazy(() => associatedSipPeerSchema))),
    { xmlName: 'AssociatedSipPeer' },
  ],
});
