/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface Attributes {
  empty?: boolean;
}

export const attributesSchema: Schema<Attributes> = object({
  empty: ['empty', optional(boolean())],
});
