/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AttributeProvisionTypeEnum
 */
export enum AttributeProvisionTypeEnum {
  ACCOUNT = 'ACCOUNT',
  ELEMENT = 'ELEMENT',
  GATEWAY = 'GATEWAY',
  MTAP = 'MTAP',
  MTEP = 'MTEP',
  MOAP = 'MOAP',
  MOEP = 'MOEP',
}

/**
 * Schema for AttributeProvisionTypeEnum
 */
export const attributeProvisionTypeEnumSchema: Schema<AttributeProvisionTypeEnum> = stringEnum(AttributeProvisionTypeEnum);
