/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AuditPeriod {
  startDate?: string;
  endDate?: string;
  auditMonth?: string;
}

export const auditPeriodSchema: Schema<AuditPeriod> = object({
  startDate: ['startDate', optional(string()), { xmlName: 'StartDate' }],
  endDate: ['endDate', optional(string()), { xmlName: 'EndDate' }],
  auditMonth: ['auditMonth', optional(string()), { xmlName: 'Month' }],
});
