/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface BasicAuthenticationCredentials {
  username?: string;
  password?: string;
}

export const basicAuthenticationCredentialsSchema: Schema<BasicAuthenticationCredentials> = object(
  {
    username: ['username', optional(string()), { xmlName: 'Username' }],
    password: ['password', optional(string()), { xmlName: 'Password' }],
  }
);
