/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface BdrArchiveCreationDescriptor {
  startDate?: string;
  endDate?: string;
}

export const bdrArchiveCreationDescriptorSchema: Schema<BdrArchiveCreationDescriptor> = object(
  {
    startDate: ['startDate', optional(string()), { xmlName: 'StartDate' }],
    endDate: ['endDate', optional(string()), { xmlName: 'EndDate' }],
  }
);
