/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface BdrArchiveRetrievalResponse {
  infoMessage?: string;
}

export const bdrArchiveRetrievalResponseSchema: Schema<BdrArchiveRetrievalResponse> = object(
  { infoMessage: ['infoMessage', optional(string()), { xmlName: 'Info' }] }
);
