/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { BillingReport, billingReportSchema } from './billingReport';

export interface BillingReportsRetrievePayload {
  billingReportList?: BillingReport[];
}

export const billingReportsRetrievePayloadSchema: Schema<BillingReportsRetrievePayload> = object(
  {
    billingReportList: [
      'billingReportList',
      optional(array(lazy(() => billingReportSchema))),
      { xmlName: 'BillingReport' },
    ],
  }
);
