/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BillingTypeEnum
 */
export enum BillingTypeEnum {
  NOCHARGE = 'NOCHARGE',
  PORTIN = 'PORTIN',
  NEWNUMBER = 'NEWNUMBER',
  PROJECTPORT = 'PROJECTPORT',
  DISCOUNTED = 'DISCOUNTED',
}

/**
 * Schema for BillingTypeEnum
 */
export const billingTypeEnumSchema: Schema<BillingTypeEnum> = stringEnum(BillingTypeEnum);
