/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  BillingReportDateRange,
  billingReportDateRangeSchema,
} from './billingReportDateRange';

export interface BillingReport {
  id?: string;
  type?: string;
  requestedBy?: string;
  status?: string;
  description?: string;
  createdAt?: string;
  dateRange?: BillingReportDateRange;
}

export const billingReportSchema: Schema<BillingReport> = object({
  id: ['id', optional(string()), { xmlName: 'BillingReportId' }],
  type: ['type', optional(string()), { xmlName: 'BillingReportKind' }],
  requestedBy: ['requestedBy', optional(string()), { xmlName: 'UserId' }],
  status: ['status', optional(string()), { xmlName: 'ReportStatus' }],
  description: ['description', optional(string()), { xmlName: 'Description' }],
  createdAt: ['createdAt', optional(string()), { xmlName: 'CreatedDate' }],
  dateRange: [
    'dateRange',
    optional(lazy(() => billingReportDateRangeSchema)),
    { xmlName: 'DateRange' },
  ],
});
