/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema';
import { ActionTypeEnum, actionTypeEnumSchema } from './actionTypeEnum';
import { AuditPeriod, auditPeriodSchema } from './auditPeriod';

export interface BillingTask {
  auditPeriod?: AuditPeriod;
  actionType?: ActionTypeEnum;
  regenerated?: boolean;
}

export const billingTaskSchema: Schema<BillingTask> = object({
  auditPeriod: [
    'auditPeriod',
    optional(lazy(() => auditPeriodSchema)),
    { xmlName: 'Period' },
  ],
  actionType: [
    'actionType',
    optional(actionTypeEnumSchema),
    { xmlName: 'Type' },
  ],
  regenerated: ['regenerated', optional(boolean()), { xmlName: 'Regenerated' }],
});
