/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { BillingSetting, billingSettingSchema } from './billingSetting';

export interface BillingSettings {
  billingSettings?: BillingSetting[];
}

export const billingSettingsSchema: Schema<BillingSettings> = object({
  billingSettings: [
    'billingSettings',
    optional(array(lazy(() => billingSettingSchema))),
    { xmlName: 'BillingSetting' },
  ],
});
