/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { BillingSettings, billingSettingsSchema } from './billingSettings';

export interface BillingSettingsResponse {
  payload?: BillingSettings;
}

export const billingSettingsResponseSchema: Schema<BillingSettingsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => billingSettingsSchema)),
      { xmlName: 'BillingSettings' },
    ],
  }
);
