/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { BocAccount, bocAccountSchema } from './bocAccount';
import { OperationEnum, operationEnumSchema } from './operationEnum';

export interface BocAccountList {
  countryCode?: string;
  operation?: OperationEnum;
  accountList?: BocAccount[];
}

export const bocAccountListSchema: Schema<BocAccountList> = object({
  countryCode: ['countryCode', optional(string()), { xmlName: 'Country' }],
  operation: [
    'operation',
    optional(operationEnumSchema),
    { xmlName: 'Operation' },
  ],
  accountList: [
    'accountList',
    optional(array(lazy(() => bocAccountSchema), { xmlItemName: 'Account' })),
    { xmlName: 'Accounts' },
  ],
});
