/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface BocAccount {
  accountId?: number;
  updateAllLocations?: boolean;
  errorStatus?: string;
}

export const bocAccountSchema: Schema<BocAccount> = object({
  accountId: ['accountId', optional(number()), { xmlName: 'AccountId' }],
  updateAllLocations: [
    'updateAllLocations',
    optional(boolean()),
    { xmlName: 'AllLocations' },
  ],
  errorStatus: ['errorStatus', optional(string()), { xmlName: 'Status' }],
});
