/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface BreakOutCountry {
  name?: string;
  alpha3Code?: string;
  countryCode?: number;
  prefixDigits?: number[];
  authRequired?: boolean;
  billingEnabled?: boolean;
}

export const breakOutCountrySchema: Schema<BreakOutCountry> = object({
  name: ['name', optional(string()), { xmlName: 'Name' }],
  alpha3Code: ['alpha3Code', optional(string()), { xmlName: 'Alpha3Code' }],
  countryCode: ['countryCode', optional(number()), { xmlName: 'CountryCode' }],
  prefixDigits: [
    'prefixDigits',
    optional(array(number(), { xmlItemName: 'Digits' })),
    { xmlName: 'PrefixDigits' },
  ],
  authRequired: [
    'authRequired',
    optional(boolean()),
    { xmlName: 'AuthRequired' },
  ],
  billingEnabled: [
    'billingEnabled',
    optional(boolean()),
    { xmlName: 'BillingEnabled' },
  ],
});
