/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';
import { SupplementalEnum, supplementalEnumSchema } from './supplementalEnum';

export interface BulkPortout {
  pon?: string;
  pin?: string;
  newSpid?: string;
  focDate?: string;
  supplemental?: SupplementalEnum;
  immediately?: boolean;
  telephoneNumbers?: string[];
  callbackUrl?: string;
  internalPort?: boolean;
  accountNumber?: string;
  zip?: string;
  subscriberName?: string;
  overrideValidation?: boolean;
  skipPortPsCheck?: boolean;
}

export const bulkPortoutSchema: Schema<BulkPortout> = object({
  pon: ['pon', optional(string()), { xmlName: 'PON' }],
  pin: ['pin', optional(string()), { xmlName: 'Pin' }],
  newSpid: ['newSpid', optional(string()), { xmlName: 'NewNetworkSPID' }],
  focDate: ['focDate', optional(string()), { xmlName: 'FocDate' }],
  supplemental: [
    'supplemental',
    optional(supplementalEnumSchema),
    { xmlName: 'Supplemental' },
  ],
  immediately: ['immediately', optional(boolean()), { xmlName: 'Immediately' }],
  telephoneNumbers: [
    'telephoneNumbers',
    optional(array(string(), { xmlItemName: 'TelephoneNumberToPort' })),
    { xmlName: 'TelephoneNumberList' },
  ],
  callbackUrl: ['callbackUrl', optional(string()), { xmlName: 'CallbackUrl' }],
  internalPort: [
    'internalPort',
    optional(boolean()),
    { xmlName: 'InternalPort' },
  ],
  accountNumber: [
    'accountNumber',
    optional(string()),
    { xmlName: 'AccountNumber' },
  ],
  zip: ['zip', optional(string()), { xmlName: 'ZipCode' }],
  subscriberName: [
    'subscriberName',
    optional(string()),
    { xmlName: 'SubscriberName' },
  ],
  overrideValidation: [
    'overrideValidation',
    optional(boolean()),
    { xmlName: 'OverrideValidation' },
  ],
  skipPortPsCheck: [
    'skipPortPsCheck',
    optional(boolean()),
    { xmlName: 'SkipPortPsCheck' },
  ],
});
