/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface BulkTnList {
  tns?: string[];
}

export const bulkTnListSchema: Schema<BulkTnList> = object({
  tns: ['tns', optional(array(string())), { xmlName: 'TN' }],
});
