/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ProcessingStatus8Enum,
  processingStatus8EnumSchema,
} from './processingStatus8Enum';
import { Subscriber, subscriberSchema } from './subscriber';

export interface BulkPortin {
  orderId?: string;
  customerOrderId?: string;
  requestedFocDate?: string;
  alternateSpid?: string;
  billingTelephoneNumber?: string;
  subscriber?: Subscriber;
  loaAuthorizingPerson?: string;
  accountNumber?: string;
  pinNumber?: string;
  siteId?: number;
  peerId?: number;
  processingStatus?: ProcessingStatus8Enum;
  tnAttributes?: string[];
  accountId?: number;
  actualFocDate?: string;
  createdByUser?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  orderCreateDate?: string;
}

export const bulkPortinSchema: Schema<BulkPortin> = object({
  orderId: ['orderId', optional(string()), { xmlName: 'OrderId' }],
  customerOrderId: [
    'customerOrderId',
    optional(string()),
    { xmlName: 'CustomerOrderId' },
  ],
  requestedFocDate: [
    'requestedFocDate',
    optional(string()),
    { xmlName: 'RequestedFocDate' },
  ],
  alternateSpid: [
    'alternateSpid',
    optional(string()),
    { xmlName: 'AlternateSpid' },
  ],
  billingTelephoneNumber: [
    'billingTelephoneNumber',
    optional(string()),
    { xmlName: 'BillingTelephoneNumber' },
  ],
  subscriber: [
    'subscriber',
    optional(lazy(() => subscriberSchema)),
    { xmlName: 'Subscriber' },
  ],
  loaAuthorizingPerson: [
    'loaAuthorizingPerson',
    optional(string()),
    { xmlName: 'LoaAuthorizingPerson' },
  ],
  accountNumber: [
    'accountNumber',
    optional(string()),
    { xmlName: 'AccountNumber' },
  ],
  pinNumber: ['pinNumber', optional(string()), { xmlName: 'PinNumber' }],
  siteId: ['siteId', optional(number()), { xmlName: 'SiteId' }],
  peerId: ['peerId', optional(number()), { xmlName: 'PeerId' }],
  processingStatus: [
    'processingStatus',
    optional(processingStatus8EnumSchema),
    { xmlName: 'ProcessingStatus' },
  ],
  tnAttributes: [
    'tnAttributes',
    optional(array(string(), { xmlItemName: 'TnAttribute' })),
    { xmlName: 'TnAttributes' },
  ],
  accountId: ['accountId', optional(number()), { xmlName: 'AccountId' }],
  actualFocDate: [
    'actualFocDate',
    optional(string()),
    { xmlName: 'ActualFocDate' },
  ],
  createdByUser: [
    'createdByUser',
    optional(string()),
    { xmlName: 'CreatedByUser' },
  ],
  lastModifiedBy: [
    'lastModifiedBy',
    optional(string()),
    { xmlName: 'LastModifiedBy' },
  ],
  lastModifiedDate: [
    'lastModifiedDate',
    optional(string()),
    { xmlName: 'LastModifiedDate' },
  ],
  orderCreateDate: [
    'orderCreateDate',
    optional(string()),
    { xmlName: 'OrderCreateDate' },
  ],
});
