/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface BulkPortinList {
  portinOrderIds?: string[];
}

export const bulkPortinListSchema: Schema<BulkPortinList> = object({
  portinOrderIds: [
    'portinOrderIds',
    optional(array(string())),
    { xmlName: 'PortinOrderId' },
  ],
});
