/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface BwspidsSystemValue {
  id?: number;
  routeType?: string;
  priority?: number;
  spid?: string;
  type?: string;
  alias?: string;
}

export const bwspidsSystemValueSchema: Schema<BwspidsSystemValue> = object({
  id: ['id', optional(number()), { xmlName: 'Id' }],
  routeType: ['routeType', optional(string()), { xmlName: 'RouteType' }],
  priority: ['priority', optional(number()), { xmlName: 'Priority' }],
  spid: ['spid', optional(string()), { xmlName: 'Spid' }],
  type: ['type', optional(string()), { xmlName: 'Type' }],
  alias: ['alias', optional(string()), { xmlName: 'Alias' }],
});
