/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CallbackCreds {
  userId?: string;
  password?: string;
}

export const callbackCredsSchema: Schema<CallbackCreds> = object({
  userId: ['userId', optional(string()), { xmlName: 'UserId' }],
  password: ['password', optional(string()), { xmlName: 'Password' }],
});
