/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface CallAdmissionControlSettings {
  cps?: number;
  concurrentCalls?: number;
}

export const callAdmissionControlSettingsSchema: Schema<CallAdmissionControlSettings> = object(
  {
    cps: ['cps', optional(number()), { xmlName: 'CPS' }],
    concurrentCalls: [
      'concurrentCalls',
      optional(number()),
      { xmlName: 'ConcurrentCalls' },
    ],
  }
);
