/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CarrierMaskTypeEnum
 */
export enum CarrierMaskTypeEnum {
  NPANXX = 'NPANXX',
  GLOBAL = 'GLOBAL',
  INTERNATIONAL = 'INTERNATIONAL',
}

/**
 * Schema for CarrierMaskTypeEnum
 */
export const carrierMaskTypeEnumSchema: Schema<CarrierMaskTypeEnum> = stringEnum(CarrierMaskTypeEnum);
