/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { CarrierMaskFile, carrierMaskFileSchema } from './carrierMaskFile';

export interface CarrierMaskFileResponse {
  payload?: CarrierMaskFile;
}

export const carrierMaskFileResponseSchema: Schema<CarrierMaskFileResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => carrierMaskFileSchema)),
      { xmlName: 'CarrierMaskFile' },
    ],
  }
);
