/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface CarrierMaskFile {
  id?: number;
  carrierMaskName?: string;
  fileName?: string;
  fileBytes?: string[];
  carrierMaskType?: string;
}

export const carrierMaskFileSchema: Schema<CarrierMaskFile> = object({
  id: ['id', optional(number())],
  carrierMaskName: ['carrierMaskName', optional(string())],
  fileName: ['fileName', optional(string())],
  fileBytes: ['fileBytes', optional(array(string()))],
  carrierMaskType: ['carrierMaskType', optional(string())],
});
