/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CheckingModeEnum
 */
export enum CheckingModeEnum {
  FALSE = 'FALSE',
  TRUE = 'TRUE',
  ONNETPORTABILITY = 'ONNETPORTABILITY',
  OFFNETPORTABILITY = 'OFFNETPORTABILITY',
}

/**
 * Schema for CheckingModeEnum
 */
export const checkingModeEnumSchema: Schema<CheckingModeEnum> = stringEnum(CheckingModeEnum);
