/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface CitySearchAndOrderType {
  quantity?: number;
  city?: string;
  state?: string;
}

export const citySearchAndOrderTypeSchema: Schema<CitySearchAndOrderType> = object(
  {
    quantity: ['quantity', optional(number()), { xmlName: 'Quantity' }],
    city: ['city', optional(string()), { xmlName: 'City' }],
    state: ['state', optional(string()), { xmlName: 'State' }],
  }
);
