/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Host, hostSchema } from './host';

export interface CnamDipSettings {
  sustainedRequestRate?: number;
  burstRequestRate?: number;
  sourceIps?: Host[];
}

export const cnamDipSettingsSchema: Schema<CnamDipSettings> = object({
  sustainedRequestRate: [
    'sustainedRequestRate',
    optional(number()),
    { xmlName: 'SustainedRequestRate' },
  ],
  burstRequestRate: [
    'burstRequestRate',
    optional(number()),
    { xmlName: 'BurstRequestRate' },
  ],
  sourceIps: [
    'sourceIps',
    optional(array(lazy(() => hostSchema), { xmlItemName: 'Host' })),
    { xmlName: 'SourceIps' },
  ],
});
