/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ConnectionTypeEnum
 */
export enum ConnectionTypeEnum {
  TRANSCEIVER = 'TRANSCEIVER',
  SENDERONLY = 'SENDER_ONLY',
  RECEIVERONLY = 'RECEIVER_ONLY',
}

/**
 * Schema for ConnectionTypeEnum
 */
export const connectionTypeEnumSchema: Schema<ConnectionTypeEnum> = stringEnum(ConnectionTypeEnum);
