/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ConnectionTypeDefaultEnum
 */
export enum ConnectionTypeDefaultEnum {
  TRANSCEIVER = 'TRANSCEIVER',
  SENDERONLY = 'SENDER_ONLY',
  RECEIVERONLY = 'RECEIVER_ONLY',
}

/**
 * Schema for ConnectionTypeDefaultEnum
 */
export const connectionTypeDefaultEnumSchema: Schema<ConnectionTypeDefaultEnum> = stringEnum(ConnectionTypeDefaultEnum);
