/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Contact {
  firstName?: string;
  lastName?: string;
  suffix?: string;
  title?: string;
  phone?: string;
  fax?: string;
  mobile?: string;
  otherPhone?: string;
  email?: string;
  websiteAddress?: string;
}

export const contactSchema: Schema<Contact> = object({
  firstName: ['firstName', optional(string()), { xmlName: 'FirstName' }],
  lastName: ['lastName', optional(string()), { xmlName: 'LastName' }],
  suffix: ['suffix', optional(string()), { xmlName: 'Suffix' }],
  title: ['title', optional(string()), { xmlName: 'Title' }],
  phone: ['phone', optional(string()), { xmlName: 'Phone' }],
  fax: ['fax', optional(string()), { xmlName: 'Fax' }],
  mobile: ['mobile', optional(string()), { xmlName: 'Mobile' }],
  otherPhone: ['otherPhone', optional(string()), { xmlName: 'OtherPhone' }],
  email: ['email', optional(string()), { xmlName: 'Email' }],
  websiteAddress: [
    'websiteAddress',
    optional(string()),
    { xmlName: 'WebsiteAddress' },
  ],
});
