/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { BillingTask, billingTaskSchema } from './billingTask';

export interface ControlPointResponse {
  payload?: BillingTask;
}

export const controlPointResponseSchema: Schema<ControlPointResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => billingTaskSchema)),
    { xmlName: 'BillingTask' },
  ],
});
