/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface CoveredRateCenter {
  id?: number;
  name?: string;
  abbreviation?: string;
  state?: string;
  lata?: number;
  availableNumberCount?: number;
  limitedAvailableNumberCount?: number;
  zipCodes?: string[];
  cities?: string[];
  vendors?: string[];
  tiers?: string[];
  npaNxxXs?: string[];
  npas?: string[];
  localRateCenterIds?: number[];
}

export const coveredRateCenterSchema: Schema<CoveredRateCenter> = object({
  id: ['id', optional(number()), { xmlName: 'Id' }],
  name: ['name', optional(string()), { xmlName: 'Name' }],
  abbreviation: [
    'abbreviation',
    optional(string()),
    { xmlName: 'Abbreviation' },
  ],
  state: ['state', optional(string()), { xmlName: 'State' }],
  lata: ['lata', optional(number()), { xmlName: 'Lata' }],
  availableNumberCount: [
    'availableNumberCount',
    optional(number()),
    { xmlName: 'AvailableNumberCount' },
  ],
  limitedAvailableNumberCount: [
    'limitedAvailableNumberCount',
    optional(number()),
    { xmlName: 'LimitedAvailableNumberCount' },
  ],
  zipCodes: ['ZipCodes', optional(array(string(), { xmlItemName: 'ZipCode' }))],
  cities: ['Cities', optional(array(string(), { xmlItemName: 'City' }))],
  vendors: ['Vendors', optional(array(string(), { xmlItemName: 'Vendor' }))],
  tiers: ['Tiers', optional(array(string(), { xmlItemName: 'Tier' }))],
  npaNxxXs: ['NpaNxxXs', optional(array(string(), { xmlItemName: 'NpaNxxX' }))],
  npas: ['Npas', optional(array(string(), { xmlItemName: 'Npa' }))],
  localRateCenterIds: [
    'LocalRateCenterIds',
    optional(array(number(), { xmlItemName: 'RateCenterId' })),
    { xmlName: 'LocalRateCenters' },
  ],
});
