/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeckTypeEnum
 */
export enum DeckTypeEnum {
  NPANXX = 'NPANXX',
  LATAOCN = 'LATAOCN',
}

/**
 * Schema for DeckTypeEnum
 */
export const deckTypeEnumSchema: Schema<DeckTypeEnum> = stringEnum(DeckTypeEnum);
