/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface DetailedTelephoneNumberStatus {
  tn?: string;
  tnStatus?: string;
  userId?: string;
  spid?: string;
  altSpid?: string;
  lrn?: string;
  ocn?: string;
  lastModifiedDateInUtc?: string;
  orderCreatedDateInUtc?: string;
  errorMessage?: string;
  accountId?: number;
  vendorId?: string;
  lnpLosingCarrierName?: string;
  orderId?: string;
  orderType?: string;
  orderStatus?: string;
}

export const detailedTelephoneNumberStatusSchema: Schema<DetailedTelephoneNumberStatus> = object(
  {
    tn: ['tn', optional(string())],
    tnStatus: ['tnStatus', optional(string()), { xmlName: 'Status' }],
    userId: ['userId', optional(string()), { xmlName: 'UserId' }],
    spid: ['spid', optional(string()), { xmlName: 'Spid' }],
    altSpid: ['altSpid', optional(string()), { xmlName: 'AltSpid' }],
    lrn: ['lrn', optional(string()), { xmlName: 'Lrn' }],
    ocn: ['ocn', optional(string()), { xmlName: 'Ocn' }],
    lastModifiedDateInUtc: [
      'lastModifiedDateInUtc',
      optional(string()),
      { xmlName: 'LastModifiedDate' },
    ],
    orderCreatedDateInUtc: [
      'orderCreatedDateInUtc',
      optional(string()),
      { xmlName: 'OrderCreateDate' },
    ],
    errorMessage: [
      'errorMessage',
      optional(string()),
      { xmlName: 'ErrorMessage' },
    ],
    accountId: ['accountId', optional(number()), { xmlName: 'AccountId' }],
    vendorId: ['vendorId', optional(string()), { xmlName: 'VendorId' }],
    lnpLosingCarrierName: [
      'lnpLosingCarrierName',
      optional(string()),
      { xmlName: 'LNPLosingCarrierName' },
    ],
    orderId: ['orderId', optional(string()), { xmlName: 'OrderId' }],
    orderType: ['orderType', optional(string()), { xmlName: 'OrderType' }],
    orderStatus: [
      'orderStatus',
      optional(string()),
      { xmlName: 'OrderStatus' },
    ],
  }
);
