/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  TelephoneNumbers1,
  telephoneNumbers1Schema,
} from './telephoneNumbers1';

export interface DisconnectTelephoneNumberOrderType {
  telephoneNumbers?: TelephoneNumbers1;
  disconnectMode?: string;
  protectedAttribute?: string;
}

export const disconnectTelephoneNumberOrderTypeSchema: Schema<DisconnectTelephoneNumberOrderType> = object(
  {
    telephoneNumbers: [
      'telephoneNumbers',
      optional(lazy(() => telephoneNumbers1Schema)),
      { xmlName: 'TelephoneNumberList' },
    ],
    disconnectMode: [
      'disconnectMode',
      optional(string()),
      { xmlName: 'DisconnectMode' },
    ],
    protectedAttribute: [
      'protectedAttribute',
      optional(string()),
      { xmlName: 'Protected' },
    ],
  }
);
