/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  DisconnectTelephoneNumberOrderType,
  disconnectTelephoneNumberOrderTypeSchema,
} from './disconnectTelephoneNumberOrderType';

export interface DisconnectTelephoneNumberOrder {
  id?: string;
  name?: string;
  lastModifiedBy?: string;
  customerOrderId?: string;
  orderCreateDate?: string;
  orderType?: DisconnectTelephoneNumberOrderType;
}

export const disconnectTelephoneNumberOrderSchema: Schema<DisconnectTelephoneNumberOrder> = object(
  {
    id: ['id', optional(string())],
    name: ['name', optional(string()), { xmlName: 'Name' }],
    lastModifiedBy: [
      'lastModifiedBy',
      optional(string()),
      { xmlName: 'LastModifiedBy' },
    ],
    customerOrderId: [
      'customerOrderId',
      optional(string()),
      { xmlName: 'CustomerOrderId' },
    ],
    orderCreateDate: [
      'orderCreateDate',
      optional(string()),
      { xmlName: 'OrderCreateDate' },
    ],
    orderType: [
      'orderType',
      optional(lazy(() => disconnectTelephoneNumberOrderTypeSchema)),
      { xmlName: 'DisconnectTelephoneNumberOrderType' },
    ],
  }
);
