/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DlrEnum
 */
export enum DlrEnum {
  INTERMEDIATE = 'INTERMEDIATE',
  FINAL = 'FINAL',
}

/**
 * Schema for DlrEnum
 */
export const dlrEnumSchema: Schema<DlrEnum> = stringEnum(DlrEnum);
