/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Domain, domainSchema } from './domain';

export interface Domains {
  domains?: Domain[];
}

export const domainsSchema: Schema<Domains> = object({
  domains: [
    'domains',
    optional(array(lazy(() => domainSchema))),
    { xmlName: 'Domain' },
  ],
});
