/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface Domain {
  name?: string;
  description?: string;
  settings?: string[];
}

export const domainSchema: Schema<Domain> = object({
  name: ['name', optional(string()), { xmlName: 'DomainName' }],
  description: [
    'description',
    optional(string()),
    { xmlName: 'DomainDescription' },
  ],
  settings: [
    'settings',
    optional(array(string(), { xmlItemName: 'DomainSetting' })),
    { xmlName: 'DomainSettings' },
  ],
});
