/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Domains, domainsSchema } from './domains';

export interface DomainsResponse {
  payload?: Domains;
}

export const domainsResponseSchema: Schema<DomainsResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => domainsSchema)),
    { xmlName: 'DomainList' },
  ],
});
