/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Domain, domainSchema } from './domain';

export interface DomainResponse {
  payload?: Domain;
}

export const domainResponseSchema: Schema<DomainResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => domainSchema)),
    { xmlName: 'Domain' },
  ],
});
