/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DstNpiEnum
 */
export enum DstNpiEnum {
  DEFAULT = 'DEFAULT',
  UNKNOWN = 'UNKNOWN',
  E164 = 'E164',
  X121 = 'X121',
  TELEX = 'TELEX',
  NATIONAL = 'NATIONAL',
  PRIVATE = 'PRIVATE',
  ERMES = 'ERMES',
  EXTENSION = 'EXTENSION',
}

/**
 * Schema for DstNpiEnum
 */
export const dstNpiEnumSchema: Schema<DstNpiEnum> = stringEnum(DstNpiEnum);
