/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DstTonEnum
 */
export enum DstTonEnum {
  DEFAULT = 'DEFAULT',
  UNKNOWN = 'UNKNOWN',
  INTERNATIONAL = 'INTERNATIONAL',
  NATIONAL = 'NATIONAL',
  NETWORKSPECIFIC = 'NETWORKSPECIFIC',
  SUBSCRIBER = 'SUBSCRIBER',
  ALPHANUMERIC = 'ALPHANUMERIC',
  ABBREVIATED = 'ABBREVIATED',
  EXTENSION = 'EXTENSION',
}

/**
 * Schema for DstTonEnum
 */
export const dstTonEnumSchema: Schema<DstTonEnum> = stringEnum(DstTonEnum);
