/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { E911Host, e911HostSchema } from './e911Host';

export interface E911Settings {
  dashUserId?: string;
  dashPassword?: string;
  dashAuthenticationStatus?: string;
  hosts?: E911Host[];
}

export const e911SettingsSchema: Schema<E911Settings> = object({
  dashUserId: ['dashUserId', optional(string()), { xmlName: 'DashUserId' }],
  dashPassword: [
    'dashPassword',
    optional(string()),
    { xmlName: 'DashPassword' },
  ],
  dashAuthenticationStatus: [
    'dashAuthenticationStatus',
    optional(string()),
    { xmlName: 'DashAuthenticationStatus' },
  ],
  hosts: [
    'hosts',
    optional(array(lazy(() => e911HostSchema), { xmlItemName: 'Host' })),
    { xmlName: 'Hosts' },
  ],
});
