/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import {
  PreferredLanguageEnum,
  preferredLanguageEnumSchema,
} from './preferredLanguageEnum';

export interface E911AlternateEndUserIdentifier {
  identifier?: string;
  callbackNumber?: string;
  pidfloEnabled?: boolean;
  callerName?: string;
  preferredLanguage?: PreferredLanguageEnum;
  locationId?: string;
}

export const e911AlternateEndUserIdentifierSchema: Schema<E911AlternateEndUserIdentifier> = object(
  {
    identifier: ['identifier', optional(string()), { xmlName: 'Identifier' }],
    callbackNumber: [
      'callbackNumber',
      optional(string()),
      { xmlName: 'CallbackNumber' },
    ],
    pidfloEnabled: [
      'pidfloEnabled',
      optional(boolean()),
      { xmlName: 'PIDFLOEnabled' },
    ],
    callerName: ['callerName', optional(string()), { xmlName: 'CallerName' }],
    preferredLanguage: [
      'preferredLanguage',
      optional(preferredLanguageEnumSchema),
      { xmlName: 'PreferredLanguage' },
    ],
    locationId: ['locationId', optional(string()), { xmlName: 'LocationId' }],
  }
);
