/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface E911Host {
  hostName?: string;
  port?: string;
}

export const e911HostSchema: Schema<E911Host> = object({
  hostName: ['hostName', optional(string()), { xmlName: 'HostName' }],
  port: ['port', optional(string()), { xmlName: 'Port' }],
});
