/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { E911Settings, e911SettingsSchema } from './e911Settings';

export interface E911SettingsResponse {
  payload?: E911Settings;
}

export const e911SettingsResponseSchema: Schema<E911SettingsResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => e911SettingsSchema)),
    { xmlName: 'E911Settings' },
  ],
});
