/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface EepToEngAssociationsPayload {
  tnList?: string[];
  aeuiList?: string[];
}

export const eepToEngAssociationsPayloadSchema: Schema<EepToEngAssociationsPayload> = object(
  {
    tnList: [
      'tnList',
      optional(array(string(), { xmlItemName: 'TelephoneNumber' })),
      { xmlName: 'EepTns' },
    ],
    aeuiList: [
      'aeuiList',
      optional(array(string(), { xmlItemName: 'Identifier' })),
      { xmlName: 'EepAeuiIds' },
    ],
  }
);
