/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  DigestRequestedEnum,
  digestRequestedEnumSchema,
} from './digestRequestedEnum';

export interface EmailSubscription {
  email?: string;
  digestRequested?: DigestRequestedEnum;
}

export const emailSubscriptionSchema: Schema<EmailSubscription> = object({
  email: ['email', optional(string()), { xmlName: 'Email' }],
  digestRequested: [
    'digestRequested',
    optional(digestRequestedEnumSchema),
    { xmlName: 'DigestRequested' },
  ],
});
