/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  EmergencyNotificationGroupsEndpointAssociationPayload,
  emergencyNotificationGroupsEndpointAssociationPayloadSchema,
} from './emergencyNotificationGroupsEndpointAssociationPayload';
import { PaginationLinks, paginationLinksSchema } from './paginationLinks';

export interface EmergencyNotificationGroupsEndpointAssociationResponse {
  payload?: EmergencyNotificationGroupsEndpointAssociationPayload;
  paginationLinks?: PaginationLinks;
}

export const emergencyNotificationGroupsEndpointAssociationResponseSchema: Schema<EmergencyNotificationGroupsEndpointAssociationResponse> = object(
  {
    payload: [
      'payload',
      optional(
        lazy(() => emergencyNotificationGroupsEndpointAssociationPayloadSchema)
      ),
      { xmlName: 'EmergencyNotificationEndpointOrders' },
    ],
    paginationLinks: [
      'paginationLinks',
      optional(lazy(() => paginationLinksSchema)),
      { xmlName: 'Links' },
    ],
  }
);
