/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  EepToEngAssociationsPayload,
  eepToEngAssociationsPayloadSchema,
} from './eepToEngAssociationsPayload';

export interface EmergencyNotificationEndpointAssociationsPayload {
  emergencyNotificationGroup?: string[];
  addedAssociations?: EepToEngAssociationsPayload[];
  deletedAssociations?: EepToEngAssociationsPayload[];
  errorList?: string[];
}

export const emergencyNotificationEndpointAssociationsPayloadSchema: Schema<EmergencyNotificationEndpointAssociationsPayload> = object(
  {
    emergencyNotificationGroup: [
      'emergencyNotificationGroup',
      optional(array(string(), { xmlItemName: 'Identifier' })),
      { xmlName: 'EmergencyNotificationGroup' },
    ],
    addedAssociations: [
      'addedAssociations',
      optional(
        array(
          lazy(() => eepToEngAssociationsPayloadSchema),
          { xmlItemName: 'EepToEngAssociations' }
        )
      ),
      { xmlName: 'AddedAssociations' },
    ],
    deletedAssociations: [
      'deletedAssociations',
      optional(
        array(
          lazy(() => eepToEngAssociationsPayloadSchema),
          { xmlItemName: 'EepToEngAssociations' }
        )
      ),
      { xmlName: 'DeletedAssociations' },
    ],
    errorList: [
      'errorList',
      optional(array(string(), { xmlItemName: 'Description' })),
      { xmlName: 'ErrorList' },
    ],
  }
);
