/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  EmergencyNotificationRecipientPayload,
  emergencyNotificationRecipientPayloadSchema,
} from './emergencyNotificationRecipientPayload';

export interface EmergencyNotificationRecipientsPayload {
  payloadList?: EmergencyNotificationRecipientPayload[];
}

export const emergencyNotificationRecipientsPayloadSchema: Schema<EmergencyNotificationRecipientsPayload> = object(
  {
    payloadList: [
      'payloadList',
      optional(array(lazy(() => emergencyNotificationRecipientPayloadSchema))),
      { xmlName: 'EmergencyNotificationRecipient' },
    ],
  }
);
