/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  EmergencyNotificationGroupOrderPayload,
  emergencyNotificationGroupOrderPayloadSchema,
} from './emergencyNotificationGroupOrderPayload';

export interface EmergencyNotificationGroupRecipientOrderPayload {
  orderId?: string;
  orderCreatedDate?: string;
  createdBy?: string;
  processingStatus?: string;
  customerOrderId?: string;
  addedEmergencyNotificationGroup?: EmergencyNotificationGroupOrderPayload;
  modifiedEmergencyNotificationGroup?: EmergencyNotificationGroupOrderPayload;
  deleteEmergencyNotificationGroup?: EmergencyNotificationGroupOrderPayload;
}

export const emergencyNotificationGroupRecipientOrderPayloadSchema: Schema<EmergencyNotificationGroupRecipientOrderPayload> = object(
  {
    orderId: ['orderId', optional(string()), { xmlName: 'OrderId' }],
    orderCreatedDate: [
      'orderCreatedDate',
      optional(string()),
      { xmlName: 'OrderCreatedDate' },
    ],
    createdBy: ['createdBy', optional(string()), { xmlName: 'CreatedBy' }],
    processingStatus: [
      'processingStatus',
      optional(string()),
      { xmlName: 'ProcessingStatus' },
    ],
    customerOrderId: [
      'customerOrderId',
      optional(string()),
      { xmlName: 'CustomerOrderId' },
    ],
    addedEmergencyNotificationGroup: [
      'addedEmergencyNotificationGroup',
      optional(lazy(() => emergencyNotificationGroupOrderPayloadSchema)),
      { xmlName: 'AddedEmergencyNotificationGroup' },
    ],
    modifiedEmergencyNotificationGroup: [
      'modifiedEmergencyNotificationGroup',
      optional(lazy(() => emergencyNotificationGroupOrderPayloadSchema)),
      { xmlName: 'ModifiedEmergencyNotificationGroup' },
    ],
    deleteEmergencyNotificationGroup: [
      'deleteEmergencyNotificationGroup',
      optional(lazy(() => emergencyNotificationGroupOrderPayloadSchema)),
      { xmlName: 'DeletedEmergencyNotificationGroup' },
    ],
  }
);
