/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { EndpointResource, endpointResourceSchema } from './endpointResource';

export interface Endpoint {
  name?: string;
  path?: string;
  resources?: EndpointResource[];
}

export const endpointSchema: Schema<Endpoint> = object({
  name: ['name', optional(string()), { xmlName: 'ServerName' }],
  path: ['path', optional(string()), { xmlName: 'ServerPath' }],
  resources: [
    'resources',
    optional(
      array(lazy(() => endpointResourceSchema), { xmlItemName: 'Resources' })
    ),
    { xmlName: 'Resources' },
  ],
});
