/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EndpointTypeEnum
 */
export enum EndpointTypeEnum {
  TN = 'TN',
  IPv4 = 'IPv4',
  SIP = 'SIP',
  FQDN = 'FQDN',
}

/**
 * Schema for EndpointTypeEnum
 */
export const endpointTypeEnumSchema: Schema<EndpointTypeEnum> = stringEnum(EndpointTypeEnum);
