/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EnrNotificationTypeEnum
 */
export enum EnrNotificationTypeEnum {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  TTS = 'TTS',
  CALLBACK = 'CALLBACK',
  UNRECOGNIZEDTYPE = 'UNRECOGNIZED_TYPE',
}

/**
 * Schema for EnrNotificationTypeEnum
 */
export const enrNotificationTypeEnumSchema: Schema<EnrNotificationTypeEnum> = stringEnum(EnrNotificationTypeEnum);
