/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface EnumParameterAllowedValue {
  internalName?: string;
  displayName?: string;
  reportParameterId?: number;
  displayIndex?: number;
}

export const enumParameterAllowedValueSchema: Schema<EnumParameterAllowedValue> = object(
  {
    internalName: [
      'internalName',
      optional(string()),
      { xmlName: 'InternalName' },
    ],
    displayName: [
      'displayName',
      optional(string()),
      { xmlName: 'DisplayName' },
    ],
    reportParameterId: ['reportParameterId', optional(number())],
    displayIndex: ['displayIndex', optional(number())],
  }
);
