/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ErrorEnum, errorEnumSchema } from './errorEnum';
import { FileData, fileDataSchema } from './fileData';

export interface FileListResponse {
  resultCode: number;
  resultMessage: string;
  fileCount: number;
  fileNames?: string[];
  fileData?: FileData[];
  error?: ErrorEnum;
}

export const fileListResponseSchema: Schema<FileListResponse> = object({
  resultCode: ['resultCode', number()],
  resultMessage: ['resultMessage', string()],
  fileCount: ['fileCount', number()],
  fileNames: ['fileNames', optional(array(string()))],
  fileData: [
    'fileData',
    optional(array(lazy(() => fileDataSchema))),
    { xmlName: 'FileData' },
  ],
  error: ['error', optional(errorEnumSchema)],
});
