/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FiletypeEnum
 */
export enum FiletypeEnum {
  CSV = 'CSV',
  XLS = 'XLS',
}

/**
 * Schema for FiletypeEnum
 */
export const filetypeEnumSchema: Schema<FiletypeEnum> = stringEnum(FiletypeEnum);
