/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { Status1Enum, status1EnumSchema } from './status1Enum';

export interface GanProfileAttributeMigration {
  accountId?: number;
  status?: Status1Enum;
}

export const ganProfileAttributeMigrationSchema: Schema<GanProfileAttributeMigration> = object(
  {
    accountId: ['accountId', optional(number()), { xmlName: 'AccountId' }],
    status: ['status', optional(status1EnumSchema), { xmlName: 'Status' }],
  }
);
