/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { HolidayPayload, holidayPayloadSchema } from './holidayPayload';

export interface HolidayResponse {
  payload?: HolidayPayload;
}

export const holidayResponseSchema: Schema<HolidayResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => holidayPayloadSchema)),
    { xmlName: 'Holiday' },
  ],
});
