/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Host, hostSchema } from './host';

export interface Hosts {
  hosts?: Host[];
}

export const hostsSchema: Schema<Hosts> = object({
  hosts: [
    'hosts',
    optional(array(lazy(() => hostSchema))),
    { xmlName: 'Host' },
  ],
});
