/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  MessagingSettings,
  messagingSettingsSchema,
} from './messagingSettings';
import { SipPeer, sipPeerSchema } from './sipPeer';
import { Site, siteSchema } from './site';
import { TnOptions, tnOptionsSchema } from './tnOptions';

export interface HostedTelephoneNumberDetailHistory {
  accountId?: number;
  site?: Site;
  sipPeer?: SipPeer;
  serviceTypesOwned?: string[];
  lastModified?: string;
  messagingSettings?: MessagingSettings;
  tnAttributes?: string[];
  tnOptions?: TnOptions;
}

export const hostedTelephoneNumberDetailHistorySchema: Schema<HostedTelephoneNumberDetailHistory> = object(
  {
    accountId: ['accountId', optional(number()), { xmlName: 'AccountId' }],
    site: ['site', optional(lazy(() => siteSchema)), { xmlName: 'Site' }],
    sipPeer: [
      'sipPeer',
      optional(lazy(() => sipPeerSchema)),
      { xmlName: 'SipPeer' },
    ],
    serviceTypesOwned: [
      'serviceTypesOwned',
      optional(array(string(), { xmlItemName: 'TnAttribute' })),
      { xmlName: 'ServiceTypes' },
    ],
    lastModified: [
      'lastModified',
      optional(string()),
      { xmlName: 'LastModified' },
    ],
    messagingSettings: [
      'messagingSettings',
      optional(lazy(() => messagingSettingsSchema)),
      { xmlName: 'MessagingSettings' },
    ],
    tnAttributes: [
      'tnAttributes',
      optional(array(string(), { xmlItemName: 'TnAttribute' })),
      { xmlName: 'TnAttributes' },
    ],
    tnOptions: [
      'tnOptions',
      optional(lazy(() => tnOptionsSchema)),
      { xmlName: 'TnOptions' },
    ],
  }
);
