/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema';
import {
  CallAdmissionControlSettings,
  callAdmissionControlSettingsSchema,
} from './callAdmissionControlSettings';

export interface HttpVoiceConfigurationPayload {
  enabled?: boolean;
  callAdmissionControlSettings?: CallAdmissionControlSettings;
}

export const httpVoiceConfigurationPayloadSchema: Schema<HttpVoiceConfigurationPayload> = object(
  {
    enabled: ['enabled', optional(boolean()), { xmlName: 'Enabled' }],
    callAdmissionControlSettings: [
      'callAdmissionControlSettings',
      optional(lazy(() => callAdmissionControlSettingsSchema)),
      { xmlName: 'CallAdmissionControlSettings' },
    ],
  }
);
