/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  ImportToAccountNumberOrder,
  importToAccountNumberOrderSchema,
} from './importToAccountNumberOrder';
import { OrderError, orderErrorSchema } from './orderError';
import { OrderStatusEnum, orderStatusEnumSchema } from './orderStatusEnum';
import {
  TelephoneNumberDetail,
  telephoneNumberDetailSchema,
} from './telephoneNumberDetail';

export interface ImportToAccountNumberOrderResponse {
  orderRequest?: ImportToAccountNumberOrder;
  orderStatus?: OrderStatusEnum;
  importedTelephoneNumbers?: string[];
  errors?: OrderError[];
  provisionedTelephoneNumberDetails?: TelephoneNumberDetail[];
}

export const importToAccountNumberOrderResponseSchema: Schema<ImportToAccountNumberOrderResponse> = object(
  {
    orderRequest: [
      'orderRequest',
      optional(lazy(() => importToAccountNumberOrderSchema)),
      { xmlName: 'OrderRequest' },
    ],
    orderStatus: [
      'orderStatus',
      optional(orderStatusEnumSchema),
      { xmlName: 'OrderStatus' },
    ],
    importedTelephoneNumbers: [
      'importedTelephoneNumbers',
      optional(array(string(), { xmlItemName: 'TelephoneNumber' })),
      { xmlName: 'ImportedTelephoneNumberList' },
    ],
    errors: [
      'errors',
      optional(
        array(lazy(() => orderErrorSchema), { xmlItemName: 'OrderError' })
      ),
      { xmlName: 'ErrorList' },
    ],
    provisionedTelephoneNumberDetails: [
      'provisionedTelephoneNumberDetails',
      optional(
        array(
          lazy(() => telephoneNumberDetailSchema),
          { xmlItemName: 'TelephoneNumberDetail' }
        )
      ),
      { xmlName: 'ImportedTelephoneNumberDetailList' },
    ],
  }
);
