/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface ImportAvailableNumberOrderType {
  telephoneNumbers?: string[];
  vendorName?: string;
  accountProfileName?: string;
  gatewayProfileName?: string;
  elementProfileName?: string;
}

export const importAvailableNumberOrderTypeSchema: Schema<ImportAvailableNumberOrderType> = object(
  {
    telephoneNumbers: [
      'telephoneNumbers',
      optional(array(string(), { xmlItemName: 'TelephoneNumber' })),
      { xmlName: 'TelephoneNumberList' },
    ],
    vendorName: ['vendorName', optional(string()), { xmlName: 'VendorName' }],
    accountProfileName: [
      'accountProfileName',
      optional(string()),
      { xmlName: 'AccountProfile' },
    ],
    gatewayProfileName: [
      'gatewayProfileName',
      optional(string()),
      { xmlName: 'GatewayProfile' },
    ],
    elementProfileName: [
      'elementProfileName',
      optional(string()),
      { xmlName: 'ElementProfile' },
    ],
  }
);
