/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ImportTnError, importTnErrorSchema } from './importTnError';

export interface ImportTnCheckerPayload {
  telephoneNumbers?: string[];
  importTnErrors?: ImportTnError[];
}

export const importTnCheckerPayloadSchema: Schema<ImportTnCheckerPayload> = object(
  {
    telephoneNumbers: [
      'telephoneNumbers',
      optional(array(string(), { xmlItemName: 'TelephoneNumber' })),
      { xmlName: 'TelephoneNumbers' },
    ],
    importTnErrors: [
      'importTnErrors',
      optional(
        array(
          lazy(() => importTnErrorSchema),
          { xmlItemName: 'ImportTnErrorType' }
        )
      ),
      { xmlName: 'ImportTnErrors' },
    ],
  }
);
