/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';
import {
  ImportBillingTypeEnum,
  importBillingTypeEnumSchema,
} from './importBillingTypeEnum';

export interface ImportToAccountNumberOrderType {
  telephoneNumbers?: string[];
  vendorName?: string;
  batchId?: string;
  batchSize?: number;
  importBillingType?: ImportBillingTypeEnum;
  tnAttributes?: string[];
  initialStatus?: string;
}

export const importToAccountNumberOrderTypeSchema: Schema<ImportToAccountNumberOrderType> = object(
  {
    telephoneNumbers: [
      'telephoneNumbers',
      optional(array(string(), { xmlItemName: 'telephoneNumber' })),
      { xmlName: 'TelephoneNumberList' },
    ],
    vendorName: ['vendorName', optional(string()), { xmlName: 'VendorName' }],
    batchId: ['batchId', optional(string()), { xmlName: 'BatchId' }],
    batchSize: ['batchSize', optional(number()), { xmlName: 'BatchSize' }],
    importBillingType: [
      'importBillingType',
      optional(importBillingTypeEnumSchema),
      { xmlName: 'BillingType' },
    ],
    tnAttributes: [
      'tnAttributes',
      optional(array(string(), { xmlItemName: 'TnAttribute' })),
      { xmlName: 'TnAttributes' },
    ],
    initialStatus: [
      'initialStatus',
      optional(string()),
      { xmlName: 'InitialStatus' },
    ],
  }
);
