/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface ImportTnError {
  phoneNumbers?: string[];
  code?: number;
  errorDescription?: string;
}

export const importTnErrorSchema: Schema<ImportTnError> = object({
  phoneNumbers: [
    'phoneNumbers',
    optional(array(string(), { xmlItemName: 'TelephoneNumber' })),
    { xmlName: 'TelephoneNumbers' },
  ],
  code: ['code', optional(number()), { xmlName: 'Code' }],
  errorDescription: [
    'errorDescription',
    optional(string()),
    { xmlName: 'Description' },
  ],
});
