/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface IntegrityAuditPayload {
  rangeStart?: string;
  chunkSize?: string;
  chunksNumber?: string;
}

export const integrityAuditPayloadSchema: Schema<IntegrityAuditPayload> = object(
  {
    rangeStart: ['rangeStart', optional(string()), { xmlName: 'RangeStart' }],
    chunkSize: ['chunkSize', optional(string()), { xmlName: 'ChunkSize' }],
    chunksNumber: [
      'chunksNumber',
      optional(string()),
      { xmlName: 'ChunksNumber' },
    ],
  }
);
