/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema';

export interface InternationalVendor {
  vendorId?: number;
  supported?: boolean;
}

export const internationalVendorSchema: Schema<InternationalVendor> = object({
  vendorId: ['vendorId', optional(number()), { xmlName: 'VendorId' }],
  supported: ['supported', optional(boolean()), { xmlName: 'Supported' }],
});
