/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  IntegrityAuditPayload,
  integrityAuditPayloadSchema,
} from './integrityAuditPayload';

export interface IntegrityAuditResponse {
  payload?: IntegrityAuditPayload;
}

export const integrityAuditResponseSchema: Schema<IntegrityAuditResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => integrityAuditPayloadSchema)),
      { xmlName: 'IntegrityAuditPayload' },
    ],
  }
);
