/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { IrisAccountDto, irisAccountDtoSchema } from './irisAccountDto';

export interface IrisAccountResponse {
  payload?: IrisAccountDto;
}

export const irisAccountResponseSchema: Schema<IrisAccountResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => irisAccountDtoSchema)),
    { xmlName: 'Account' },
  ],
});
