/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { IrisStatusType, irisStatusTypeSchema } from './irisStatusType';

export interface IrisStatus {
  description?: string;
  code?: number;
  statusType?: IrisStatusType;
}

export const irisStatusSchema: Schema<IrisStatus> = object({
  description: ['description', optional(string()), { xmlName: 'Description' }],
  code: ['code', optional(number()), { xmlName: 'Code' }],
  statusType: [
    'statusType',
    optional(lazy(() => irisStatusTypeSchema)),
    { xmlName: 'IrisStatusType' },
  ],
});
