/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { IrisAccountsDto, irisAccountsDtoSchema } from './irisAccountsDto';

export interface IrisAccountsResponse {
  payload?: IrisAccountsDto;
}

export const irisAccountsResponseSchema: Schema<IrisAccountsResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => irisAccountsDtoSchema)),
    { xmlName: 'AccountList' },
  ],
});
