/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface IrisAccountDto {
  id?: number;
  name?: string;
}

export const irisAccountDtoSchema: Schema<IrisAccountDto> = object({
  id: ['id', optional(number()), { xmlName: 'AccountId' }],
  name: ['name', optional(string()), { xmlName: 'AccountName' }],
});
