/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface IrisStatusType {
  code?: number;
  description?: string;
}

export const irisStatusTypeSchema: Schema<IrisStatusType> = object({
  code: ['code', optional(number())],
  description: ['description', optional(string())],
});
