/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { IrisAccountDto, irisAccountDtoSchema } from './irisAccountDto';

export interface IrisAccountsDto {
  totalCount?: number;
  accounts?: IrisAccountDto[];
}

export const irisAccountsDtoSchema: Schema<IrisAccountsDto> = object({
  totalCount: ['totalCount', optional(number())],
  accounts: [
    'accounts',
    optional(array(lazy(() => irisAccountDtoSchema))),
    { xmlName: 'Account' },
  ],
});
