/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Key {
  id?: string;
  display?: string;
}

export const keySchema: Schema<Key> = object({
  id: ['id', optional(string()), { xmlName: 'Id' }],
  display: ['display', optional(string()), { xmlName: 'Display' }],
});
