/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface LATASearchAndOrderType {
  quantity?: number;
  lata?: string;
}

export const lATASearchAndOrderTypeSchema: Schema<LATASearchAndOrderType> = object(
  {
    quantity: ['quantity', optional(number()), { xmlName: 'Quantity' }],
    lata: ['lata', optional(string()), { xmlName: 'LATA' }],
  }
);
