/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { ShortLdapUser, shortLdapUserSchema } from './shortLdapUser';

export interface LdapUsers {
  users?: ShortLdapUser[];
  totalCount?: number;
}

export const ldapUsersSchema: Schema<LdapUsers> = object({
  users: [
    'users',
    optional(array(lazy(() => shortLdapUserSchema))),
    { xmlName: 'User' },
  ],
  totalCount: ['totalCount', optional(number())],
});
