/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { LdapRole, ldapRoleSchema } from './ldapRole';

export interface LdapRoles {
  ldapRoles?: LdapRole[];
  roleNames?: string[];
  roleIds?: string[];
}

export const ldapRolesSchema: Schema<LdapRoles> = object({
  ldapRoles: [
    'ldapRoles',
    optional(array(lazy(() => ldapRoleSchema))),
    { xmlName: 'Role' },
  ],
  roleNames: ['roleNames', optional(array(string()))],
  roleIds: ['roleIds', optional(array(string()))],
});
