/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface LdapUserPreference {
  name?: string;
  value?: string;
  options?: string[];
}

export const ldapUserPreferenceSchema: Schema<LdapUserPreference> = object({
  name: ['name', optional(string()), { xmlName: 'PreferenceName' }],
  value: ['value', optional(string()), { xmlName: 'PreferenceValue' }],
  options: [
    'options',
    optional(array(string(), { xmlItemName: 'OptionalValue' })),
    { xmlName: 'OptionalValues' },
  ],
});
