/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  LdapUserPreference,
  ldapUserPreferenceSchema,
} from './ldapUserPreference';

export interface LdapUserPreferences {
  ldapUserPreferences?: LdapUserPreference[];
  preferencesNames?: string[];
}

export const ldapUserPreferencesSchema: Schema<LdapUserPreferences> = object({
  ldapUserPreferences: [
    'ldapUserPreferences',
    optional(array(lazy(() => ldapUserPreferenceSchema))),
    { xmlName: 'UserPreference' },
  ],
  preferencesNames: [
    'preferencesNames',
    optional(array(string())),
    { xmlName: 'OptionalValue' },
  ],
});
