/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  LdapUserPreferences,
  ldapUserPreferencesSchema,
} from './ldapUserPreferences';

export interface LdapUserPreferencesResponse {
  payload?: LdapUserPreferences;
}

export const ldapUserPreferencesResponseSchema: Schema<LdapUserPreferencesResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => ldapUserPreferencesSchema)),
      { xmlName: 'UserPreferences' },
    ],
  }
);
