/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { LdapPermission, ldapPermissionSchema } from './ldapPermission';

export interface LdapPermissionResponse {
  payload?: LdapPermission;
}

export const ldapPermissionResponseSchema: Schema<LdapPermissionResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => ldapPermissionSchema)),
      { xmlName: 'Permission' },
    ],
  }
);
