/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { LdapAccount, ldapAccountSchema } from './ldapAccount';

export interface LdapAccountsDto {
  totalCount?: number;
  accounts?: LdapAccount[];
}

export const ldapAccountsDtoSchema: Schema<LdapAccountsDto> = object({
  totalCount: ['totalCount', optional(number())],
  accounts: [
    'accounts',
    optional(array(lazy(() => ldapAccountSchema))),
    { xmlName: 'Account' },
  ],
});
