/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  LineOptionOrderPayload,
  lineOptionOrderPayloadSchema,
} from './lineOptionOrderPayload';

export interface LineOptionOrderResponse {
  payload?: LineOptionOrderPayload;
}

export const lineOptionOrderResponseSchema: Schema<LineOptionOrderResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => lineOptionOrderPayloadSchema)),
      { xmlName: 'LineOptions' },
    ],
  }
);
