/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface LineOption {
  telephoneNumber?: string;
  numberFormat?: string;
  rpidFormat?: string;
  rewriteUser?: string;
  callForward?: string;
  cnamLookup?: string;
  protect?: string;
  sms?: string;
}

export const lineOptionSchema: Schema<LineOption> = object({
  telephoneNumber: [
    'telephoneNumber',
    optional(string()),
    { xmlName: 'TelephoneNumber' },
  ],
  numberFormat: [
    'numberFormat',
    optional(string()),
    { xmlName: 'NumberFormat' },
  ],
  rpidFormat: ['rpidFormat', optional(string()), { xmlName: 'RPIDFormat' }],
  rewriteUser: ['rewriteUser', optional(string()), { xmlName: 'RewriteUser' }],
  callForward: ['callForward', optional(string()), { xmlName: 'CallForward' }],
  cnamLookup: [
    'cnamLookup',
    optional(string()),
    { xmlName: 'CallingNameDisplay' },
  ],
  protect: ['protect', optional(string()), { xmlName: 'Protected' }],
  sms: ['sms', optional(string()), { xmlName: 'Sms' }],
});
