/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListingTypeEnum
 */
export enum ListingTypeEnum {
  LISTED = 'LISTED',
  NONLISTED = 'NON_LISTED',
  NONPUBLISHED = 'NON_PUBLISHED',
}

/**
 * Schema for ListingTypeEnum
 */
export const listingTypeEnumSchema: Schema<ListingTypeEnum> = stringEnum(ListingTypeEnum);
