/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';
import {
  ErrorTypeEnum1Enum,
  errorTypeEnum1EnumSchema,
} from './errorTypeEnum1Enum';

export interface LnpError {
  errorTypeEnum?: ErrorTypeEnum1Enum;
  errorDescription?: string;
  phoneNumbers?: string[];
  code?: number;
}

export const lnpErrorSchema: Schema<LnpError> = object({
  errorTypeEnum: ['errorTypeEnum', optional(errorTypeEnum1EnumSchema)],
  errorDescription: [
    'errorDescription',
    optional(string()),
    { xmlName: 'Description' },
  ],
  phoneNumbers: [
    'phoneNumbers',
    optional(array(string(), { xmlItemName: 'Tn' })),
    { xmlName: 'TelephoneNumbers' },
  ],
  code: ['code', optional(number()), { xmlName: 'Code' }],
});
