/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface LnpSettings {
  falloutManagementGrade?: string;
}

export const lnpSettingsSchema: Schema<LnpSettings> = object({
  falloutManagementGrade: [
    'falloutManagementGrade',
    optional(string()),
    { xmlName: 'FalloutManagementGrade' },
  ],
});
