/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface LongXMLWrapper {
  count?: number;
}

export const longXMLWrapperSchema: Schema<LongXMLWrapper> = object({
  count: ['count', optional(number()), { xmlName: 'Count' }],
});
