/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface LosingCarrierGroup {
  losingCarrierSpid?: string;
  losingCarrierName?: string;
  losingCarrierIsWireless?: boolean;
  losingCarrierAccountNumberRequired?: boolean;
  losingCarrierMinimumPortingInterval?: number;
  l3LosingCarrierMinimumPortingInterval?: number;
  telephoneNumbers?: string[];
}

export const losingCarrierGroupSchema: Schema<LosingCarrierGroup> = object({
  losingCarrierSpid: [
    'losingCarrierSpid',
    optional(string()),
    { xmlName: 'LosingCarrierSPID' },
  ],
  losingCarrierName: [
    'losingCarrierName',
    optional(string()),
    { xmlName: 'LosingCarrierName' },
  ],
  losingCarrierIsWireless: [
    'losingCarrierIsWireless',
    optional(boolean()),
    { xmlName: 'LosingCarrierIsWireless' },
  ],
  losingCarrierAccountNumberRequired: [
    'losingCarrierAccountNumberRequired',
    optional(boolean()),
    { xmlName: 'LosingCarrierAccountNumberRequired' },
  ],
  losingCarrierMinimumPortingInterval: [
    'losingCarrierMinimumPortingInterval',
    optional(number()),
    { xmlName: 'LosingCarrierMinimumPortingInterval' },
  ],
  l3LosingCarrierMinimumPortingInterval: [
    'l3LosingCarrierMinimumPortingInterval',
    optional(number()),
  ],
  telephoneNumbers: [
    'telephoneNumbers',
    optional(array(string(), { xmlItemName: 'Tn' })),
    { xmlName: 'TnList' },
  ],
});
