/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import {
  MessagingRouteDetailsWrapper,
  messagingRouteDetailsWrapperSchema,
} from './messagingRouteDetailsWrapper';
import {
  TnMessagingTypeEnum,
  tnMessagingTypeEnumSchema,
} from './tnMessagingTypeEnum';

export interface MessagingRoute {
  nnId?: string;
  tnMessagingType?: TnMessagingTypeEnum;
  defaultRoute?: boolean;
  detailsWrapper?: MessagingRouteDetailsWrapper;
}

export const messagingRouteSchema: Schema<MessagingRoute> = object({
  nnId: ['nnId', optional(string()), { xmlName: 'NNID' }],
  tnMessagingType: [
    'tnMessagingType',
    optional(tnMessagingTypeEnumSchema),
    { xmlName: 'TNType' },
  ],
  defaultRoute: ['defaultRoute', optional(boolean()), { xmlName: 'Default' }],
  detailsWrapper: [
    'detailsWrapper',
    optional(lazy(() => messagingRouteDetailsWrapperSchema)),
    { xmlName: 'Details' },
  ],
});
