/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { NnRoute, nnRouteSchema } from './nnRoute';

export interface MessagingRouteDetailsWrapper {
  nnRoute?: NnRoute;
}

export const messagingRouteDetailsWrapperSchema: Schema<MessagingRouteDetailsWrapper> = object(
  {
    nnRoute: [
      'nnRoute',
      optional(lazy(() => nnRouteSchema)),
      { xmlName: 'NNRoute' },
    ],
  }
);
