/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { A2pStateEnum, a2pStateEnumSchema } from './a2pStateEnum';
import { TnDetailsNnRoute, tnDetailsNnRouteSchema } from './tnDetailsNnRoute';

export interface MessagingSettings {
  smsEnabled?: string;
  campaignId?: string;
  messageClass?: string;
  a2pState?: A2pStateEnum;
  assignedNNRoute?: TnDetailsNnRoute;
}

export const messagingSettingsSchema: Schema<MessagingSettings> = object({
  smsEnabled: ['smsEnabled', optional(string()), { xmlName: 'SmsEnabled' }],
  campaignId: ['campaignId', optional(string()), { xmlName: 'CampaignId' }],
  messageClass: [
    'messageClass',
    optional(string()),
    { xmlName: 'MessageClass' },
  ],
  a2pState: ['a2pState', optional(a2pStateEnumSchema), { xmlName: 'A2pState' }],
  assignedNNRoute: [
    'assignedNNRoute',
    optional(lazy(() => tnDetailsNnRouteSchema)),
    { xmlName: 'AssignedNnRoute' },
  ],
});
