/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface MessagingBlockedAccountId {
  accountId?: string;
  lastModifiedBy?: string;
  note?: string;
}

export const messagingBlockedAccountIdSchema: Schema<MessagingBlockedAccountId> = object(
  {
    accountId: ['accountId', optional(string()), { xmlName: 'AccountId' }],
    lastModifiedBy: [
      'lastModifiedBy',
      optional(string()),
      { xmlName: 'LastModifiedBy' },
    ],
    note: ['note', optional(string()), { xmlName: 'Note' }],
  }
);
