/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { MmsSettings, mmsSettingsSchema } from './mmsSettings';

export interface MmsFeatureMmsSettingsResponse {
  payload?: MmsSettings;
}

export const mmsFeatureMmsSettingsResponseSchema: Schema<MmsFeatureMmsSettingsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => mmsSettingsSchema)),
      { xmlName: 'MmsSettings' },
    ],
  }
);
