/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerMmsFeature,
  sipPeerMmsFeatureSchema,
} from './sipPeerMmsFeature';

export interface MmsFeatureResponse {
  payload?: SipPeerMmsFeature;
}

export const mmsFeatureResponseSchema: Schema<MmsFeatureResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => sipPeerMmsFeatureSchema)),
    { xmlName: 'MmsFeature' },
  ],
});
