/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface MmsHttpSettings {
  proxyPeerId?: number;
}

export const mmsHttpSettingsSchema: Schema<MmsHttpSettings> = object({
  proxyPeerId: ['proxyPeerId', optional(number()), { xmlName: 'ProxyPeerId' }],
});
