/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { MmsHttpSettings, mmsHttpSettingsSchema } from './mmsHttpSettings';

export interface MmsHttpProtocol {
  httpSettings?: MmsHttpSettings;
}

export const mmsHttpProtocolSchema: Schema<MmsHttpProtocol> = object({
  httpSettings: [
    'httpSettings',
    optional(lazy(() => mmsHttpSettingsSchema)),
    { xmlName: 'HttpSettings' },
  ],
});
