/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface MmsMM4OrigHost {
  hostName?: string;
  port?: string;
  hostId?: number;
  priority?: number;
}

export const mmsMM4OrigHostSchema: Schema<MmsMM4OrigHost> = object({
  hostName: ['hostName', optional(string()), { xmlName: 'HostName' }],
  port: ['port', optional(string()), { xmlName: 'Port' }],
  hostId: ['hostId', optional(number()), { xmlName: 'HostId' }],
  priority: ['priority', optional(number()), { xmlName: 'Priority' }],
});
