/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { Protocol1Enum, protocol1EnumSchema } from './protocol1Enum';

export interface MmsSettings {
  protocol?: Protocol1Enum;
}

export const mmsSettingsSchema: Schema<MmsSettings> = object({
  protocol: [
    'protocol',
    optional(protocol1EnumSchema),
    { xmlName: 'Protocol' },
  ],
});
