/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema } from '../schema';

export interface NnidAccountSync {
  accountIds?: number[];
}

export const nnidAccountSyncSchema: Schema<NnidAccountSync> = object({
  accountIds: [
    'accountIds',
    optional(array(number(), { xmlItemName: 'AccountId' })),
    { xmlName: 'AccountIds' },
  ],
});
