/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface Note {
  id?: number;
  lastModifiedBy?: string;
  description?: string;
  lastModifiedDate?: string;
  internal?: boolean;
}

export const noteSchema: Schema<Note> = object({
  id: ['id', optional(number()), { xmlName: 'Id' }],
  lastModifiedBy: ['lastModifiedBy', optional(string()), { xmlName: 'UserId' }],
  description: ['description', optional(string()), { xmlName: 'Description' }],
  lastModifiedDate: [
    'lastModifiedDate',
    optional(string()),
    { xmlName: 'LastDateModifier' },
  ],
  internal: ['internal', optional(boolean()), { xmlName: 'Internal' }],
});
