/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Note, noteSchema } from './note';

export interface NotesResponse {
  notes?: Note[];
}

export const notesResponseSchema: Schema<NotesResponse> = object({
  notes: [
    'notes',
    optional(array(lazy(() => noteSchema))),
    { xmlName: 'Note' },
  ],
});
