/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface NPANXXSearchAndOrderType {
  npaNxx?: string;
  quantity?: number;
}

export const nPANXXSearchAndOrderTypeSchema: Schema<NPANXXSearchAndOrderType> = object(
  {
    npaNxx: ['npaNxx', optional(string()), { xmlName: 'NpaNxx' }],
    quantity: ['quantity', optional(number()), { xmlName: 'Quantity' }],
  }
);
