/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface NpaNxxCarrierMask {
  npaNxx?: string;
  carrierMask?: string;
}

export const npaNxxCarrierMaskSchema: Schema<NpaNxxCarrierMask> = object({
  npaNxx: ['npaNxx', optional(string())],
  carrierMask: ['carrierMask', optional(string())],
});
