/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';
import { CheckingModeEnum, checkingModeEnumSchema } from './checkingModeEnum';

export interface NumberPortabilityRequest {
  accountId?: number;
  checkingMode?: CheckingModeEnum;
  typedOrderIdToIgnoreCheck?: number;
  telephoneNumbers?: string[];
}

export const numberPortabilityRequestSchema: Schema<NumberPortabilityRequest> = object(
  {
    accountId: ['accountId', optional(number())],
    checkingMode: ['checkingMode', optional(checkingModeEnumSchema)],
    typedOrderIdToIgnoreCheck: [
      'typedOrderIdToIgnoreCheck',
      optional(number()),
    ],
    telephoneNumbers: [
      'telephoneNumbers',
      optional(array(string(), { xmlItemName: 'Tn' })),
      { xmlName: 'TnList' },
    ],
  }
);
