/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { CnamDipSettings, cnamDipSettingsSchema } from './cnamDipSettings';
import { LnpSettings, lnpSettingsSchema } from './lnpSettings';

export interface NumberManagementSettings {
  cnamDipSettings?: CnamDipSettings;
  lnpSettings?: LnpSettings;
  vendorIds?: number[];
  countries?: string[];
  tnTypeIds?: number[];
}

export const numberManagementSettingsSchema: Schema<NumberManagementSettings> = object(
  {
    cnamDipSettings: [
      'cnamDipSettings',
      optional(lazy(() => cnamDipSettingsSchema)),
      { xmlName: 'CnamDip' },
    ],
    lnpSettings: [
      'lnpSettings',
      optional(lazy(() => lnpSettingsSchema)),
      { xmlName: 'LNP' },
    ],
    vendorIds: [
      'vendorIds',
      optional(array(number(), { xmlItemName: 'VendorId' })),
      { xmlName: 'VendorIds' },
    ],
    countries: [
      'countries',
      optional(array(string(), { xmlItemName: 'CountryTwoLetterCode' })),
      { xmlName: 'Countries' },
    ],
    tnTypeIds: [
      'tnTypeIds',
      optional(array(number(), { xmlItemName: 'TnTypeId' })),
      { xmlName: 'TnTypeIds' },
    ],
  }
);
