/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { LnpError, lnpErrorSchema } from './lnpError';
import {
  LosingCarrierGroup,
  losingCarrierGroupSchema,
} from './losingCarrierGroup';
import { PortInTypeEnum, portInTypeEnumSchema } from './portInTypeEnum';
import { RateCenterGroup, rateCenterGroupSchema } from './rateCenterGroup';
import {
  TollFreeNumberGroup,
  tollFreeNumberGroupSchema,
} from './tollFreeNumberGroup';

export interface NumberPortabilityResponse {
  portInType?: PortInTypeEnum;
  errors?: LnpError[];
  supportedNumbers?: string[];
  portabilityErrors?: LnpError[];
  supportedRateCenters?: RateCenterGroup[];
  partnerSupportedRateCenters?: RateCenterGroup[];
  supportedTollFreeNumbers?: TollFreeNumberGroup[];
  unsupportedRateCenters?: RateCenterGroup[];
  supportedLosingCarriers?: LosingCarrierGroup[];
  unSupportedLosingCarriers?: LosingCarrierGroup[];
  supportedRateCenterTelephoneNumbers?: string[];
  supportedTollFreeTelephoneNumbers?: string[];
  unsupportedRateCenterTelephoneNumbers?: string[];
  unsupportedLosingCarrierTelephoneNumbers?: string[];
}

export const numberPortabilityResponseSchema: Schema<NumberPortabilityResponse> = object(
  {
    portInType: [
      'portInType',
      optional(portInTypeEnumSchema),
      { xmlName: 'PortType' },
    ],
    errors: [
      'errors',
      optional(array(lazy(() => lnpErrorSchema))),
      { xmlName: 'Errors' },
    ],
    supportedNumbers: [
      'supportedNumbers',
      optional(array(string(), { xmlItemName: 'Tn' })),
      { xmlName: 'PortableNumbers' },
    ],
    portabilityErrors: [
      'portabilityErrors',
      optional(array(lazy(() => lnpErrorSchema), { xmlItemName: 'LnpError' })),
      { xmlName: 'PortabilityErrors' },
    ],
    supportedRateCenters: [
      'supportedRateCenters',
      optional(
        array(
          lazy(() => rateCenterGroupSchema),
          { xmlItemName: 'RateCenterGroup' }
        )
      ),
      { xmlName: 'SupportedRateCenters' },
    ],
    partnerSupportedRateCenters: [
      'partnerSupportedRateCenters',
      optional(
        array(
          lazy(() => rateCenterGroupSchema),
          { xmlItemName: 'RateCenterGroup' }
        )
      ),
      { xmlName: 'PartnerSupportedRateCenters' },
    ],
    supportedTollFreeNumbers: [
      'supportedTollFreeNumbers',
      optional(
        array(
          lazy(() => tollFreeNumberGroupSchema),
          { xmlItemName: 'TollFreeNumberGroup' }
        )
      ),
      { xmlName: 'SupportedTollFreeNumbers' },
    ],
    unsupportedRateCenters: [
      'unsupportedRateCenters',
      optional(
        array(
          lazy(() => rateCenterGroupSchema),
          { xmlItemName: 'RateCenterGroup' }
        )
      ),
      { xmlName: 'UnsupportedRateCenters' },
    ],
    supportedLosingCarriers: [
      'supportedLosingCarriers',
      optional(
        array(
          lazy(() => losingCarrierGroupSchema),
          { xmlItemName: 'LosingCarrierGroup' }
        )
      ),
      { xmlName: 'SupportedLosingCarriers' },
    ],
    unSupportedLosingCarriers: [
      'unSupportedLosingCarriers',
      optional(
        array(
          lazy(() => losingCarrierGroupSchema),
          { xmlItemName: 'LosingCarrierGroup' }
        )
      ),
      { xmlName: 'UnsupportedLosingCarriers' },
    ],
    supportedRateCenterTelephoneNumbers: [
      'supportedRateCenterTelephoneNumbers',
      optional(array(string(), { xmlItemName: 'Tn' })),
      { xmlName: 'SupportedRateCenterTelephoneNumbers' },
    ],
    supportedTollFreeTelephoneNumbers: [
      'supportedTollFreeTelephoneNumbers',
      optional(array(string(), { xmlItemName: 'Tn' })),
      { xmlName: 'SupportedTollFreeTelephoneNumbers' },
    ],
    unsupportedRateCenterTelephoneNumbers: [
      'unsupportedRateCenterTelephoneNumbers',
      optional(array(string(), { xmlItemName: 'Tn' })),
      { xmlName: 'UnsupportedRateCenterTelephoneNumbers' },
    ],
    unsupportedLosingCarrierTelephoneNumbers: [
      'unsupportedLosingCarrierTelephoneNumbers',
      optional(array(string(), { xmlItemName: 'Tn' })),
      { xmlName: 'UnsupportedLosingCarrierTelephoneNumbers' },
    ],
  }
);
