/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderStatus1Enum
 */
export enum OrderStatus1Enum {
  FOC = 'FOC',
  EXCEPTION = 'EXCEPTION',
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETE',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL',
}

/**
 * Schema for OrderStatus1Enum
 */
export const orderStatus1EnumSchema: Schema<OrderStatus1Enum> = stringEnum(OrderStatus1Enum);
