/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface OrderHistory {
  orderDate?: string;
  noteDescription?: string;
  author?: string;
  orderStatus?: string;
  difference?: string;
}

export const orderHistorySchema: Schema<OrderHistory> = object({
  orderDate: ['orderDate', optional(string()), { xmlName: 'OrderDate' }],
  noteDescription: ['noteDescription', optional(string()), { xmlName: 'Note' }],
  author: ['author', optional(string()), { xmlName: 'Author' }],
  orderStatus: ['orderStatus', optional(string()), { xmlName: 'Status' }],
  difference: ['difference', optional(string()), { xmlName: 'Difference' }],
});
