/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderTypeEnum
 */
export enum OrderTypeEnum {
  BulkPortIn = 'bulk_port_in',
  PortIn = 'port_in',
  PortOut = 'port_out',
  NewNumber = 'new_number',
  Disconnect = 'disconnect',
  ImportToAccount = 'import_to_account',
  Lidb = 'lidb',
  Dlda = 'dlda',
  Lsr = 'lsr',
  E911 = 'e911',
  TnOption = 'tn_option',
  ExternalTns = 'external_tns',
  NumbersAssignment = 'numbers_assignment',
  ImportTnOrders = 'import_tn_orders',
  RemoveImportedTnOrders = 'remove_imported_tn_orders',
  Csr = 'csr',
  EmergencyNotificationGroup = 'emergency_notification_group',
  EmergencyEndpointGroup = 'emergency_endpoint_group',
}

/**
 * Schema for OrderTypeEnum
 */
export const orderTypeEnumSchema: Schema<OrderTypeEnum> = stringEnum(OrderTypeEnum);
