/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderStatusEnum
 */
export enum OrderStatusEnum {
  RECEIVED = 'RECEIVED',
  COMPLETE = 'COMPLETE',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
  BACKORDERED = 'BACKORDERED',
  PROCESSING = 'PROCESSING',
}

/**
 * Schema for OrderStatusEnum
 */
export const orderStatusEnumSchema: Schema<OrderStatusEnum> = stringEnum(OrderStatusEnum);
