/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { ErrorTypeEnum, errorTypeEnumSchema } from './errorTypeEnum';

export interface OrderError {
  errorTypeEnum?: ErrorTypeEnum;
  telephoneNumber?: string;
  code?: number;
  errorDescription?: string;
}

export const orderErrorSchema: Schema<OrderError> = object({
  errorTypeEnum: ['errorTypeEnum', optional(errorTypeEnumSchema)],
  telephoneNumber: [
    'telephoneNumber',
    optional(string()),
    { xmlName: 'TelephoneNumber' },
  ],
  code: ['code', optional(number()), { xmlName: 'Code' }],
  errorDescription: [
    'errorDescription',
    optional(string()),
    { xmlName: 'Description' },
  ],
});
