/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface OrderDetailsReport {
  city?: string;
  lata?: string;
  ratecenter?: string;
  state?: string;
  npa?: string;
  npanxx?: string;
  npanxxx?: string;
  fullNumber?: string;
  tier?: number;
  vendorId?: number;
  vendorName?: string;
  count?: number;
}

export const orderDetailsReportSchema: Schema<OrderDetailsReport> = object({
  city: ['city', optional(string()), { xmlName: 'City' }],
  lata: ['lata', optional(string()), { xmlName: 'Lata' }],
  ratecenter: ['ratecenter', optional(string()), { xmlName: 'RateCenter' }],
  state: ['state', optional(string()), { xmlName: 'State' }],
  npa: ['npa', optional(string()), { xmlName: 'AreaCode' }],
  npanxx: ['npanxx', optional(string()), { xmlName: 'NPA-NXX' }],
  npanxxx: ['npanxxx', optional(string()), { xmlName: 'NPA-NXX-X' }],
  fullNumber: ['fullNumber', optional(string()), { xmlName: 'FullNumber' }],
  tier: ['tier', optional(number()), { xmlName: 'Tier' }],
  vendorId: ['vendorId', optional(number()), { xmlName: 'VendorId' }],
  vendorName: ['vendorName', optional(string()), { xmlName: 'VendorName' }],
  count: ['count', optional(number()), { xmlName: 'Count' }],
});
