/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ActionEnum, actionEnumSchema } from './actionEnum';
import {
  OriginationRoutePayload,
  originationRoutePayloadSchema,
} from './originationRoutePayload';

export interface OriginationRoutePlan {
  id?: string;
  originationRoutes?: OriginationRoutePayload[];
  action?: ActionEnum;
}

export const originationRoutePlanSchema: Schema<OriginationRoutePlan> = object({
  id: ['id', optional(string()), { xmlName: 'Id' }],
  originationRoutes: [
    'originationRoutes',
    optional(array(lazy(() => originationRoutePayloadSchema))),
    { xmlName: 'Route' },
  ],
  action: ['action', optional(actionEnumSchema), { xmlName: 'Action' }],
});
