/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { EndpointTypeEnum, endpointTypeEnumSchema } from './endpointTypeEnum';

export interface OriginationRoutePayload {
  endpoint?: string;
  priority?: number;
  weight?: number;
  endpointType?: EndpointTypeEnum;
}

export const originationRoutePayloadSchema: Schema<OriginationRoutePayload> = object(
  {
    endpoint: ['endpoint', optional(string()), { xmlName: 'Endpoint' }],
    priority: ['priority', optional(number()), { xmlName: 'Priority' }],
    weight: ['weight', optional(number()), { xmlName: 'Weight' }],
    endpointType: [
      'endpointType',
      optional(endpointTypeEnumSchema),
      { xmlName: 'EndpointType' },
    ],
  }
);
