/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  OriginationConfigurationPayload,
  originationConfigurationPayloadSchema,
} from './originationConfigurationPayload';

export interface OriginationConfigurationResponse {
  payload?: OriginationConfigurationPayload;
}

export const originationConfigurationResponseSchema: Schema<OriginationConfigurationResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => originationConfigurationPayloadSchema)),
      { xmlName: 'OriginationSettings' },
    ],
  }
);
