/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface OriginationConfigurationPayload {
  concurrentBidirectionalCalls?: number;
  concurrentInboundCalls?: number;
  redirectEnabled?: string;
}

export const originationConfigurationPayloadSchema: Schema<OriginationConfigurationPayload> = object(
  {
    concurrentBidirectionalCalls: [
      'concurrentBidirectionalCalls',
      optional(number()),
      { xmlName: 'ConcurrentBidirectionalCalls' },
    ],
    concurrentInboundCalls: [
      'concurrentInboundCalls',
      optional(number()),
      { xmlName: 'ConcurrentInboundCalls' },
    ],
    redirectEnabled: [
      'redirectEnabled',
      optional(string()),
      { xmlName: 'RedirectEnabled' },
    ],
  }
);
