/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface Payload1 {
  empty?: boolean;
}

export const payload1Schema: Schema<Payload1> = object({
  empty: ['empty', optional(boolean())],
});
