/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface Payload4 {
  empty?: boolean;
}

export const payload4Schema: Schema<Payload4> = object({
  empty: ['empty', optional(boolean())],
});
