/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface Payload {
  empty?: boolean;
}

export const payloadSchema: Schema<Payload> = object({
  empty: ['empty', optional(boolean())],
});
