/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { PhoneNumber, phoneNumberSchema } from './phoneNumber';

export interface PhoneNumberList {
  phoneNumbers?: PhoneNumber[];
  numbersAsStrings?: string[];
}

export const phoneNumberListSchema: Schema<PhoneNumberList> = object({
  phoneNumbers: [
    'phoneNumbers',
    optional(array(lazy(() => phoneNumberSchema))),
    { xmlName: 'PhoneNumber' },
  ],
  numbersAsStrings: [
    'numbersAsStrings',
    optional(array(string())),
    { xmlName: 'TnAttribute' },
  ],
});
