/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { Type1Enum, type1EnumSchema } from './type1Enum';

export interface PomAccount {
  type?: Type1Enum;
  accountId?: number;
}

export const pomAccountSchema: Schema<PomAccount> = object({
  type: ['type', optional(type1EnumSchema), { xmlName: 'Type' }],
  accountId: ['accountId', optional(number()), { xmlName: 'AccountId' }],
});
