/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { PomAccount, pomAccountSchema } from './pomAccount';

export interface PomAccountResponse {
  payload?: PomAccount;
}

export const pomAccountResponseSchema: Schema<PomAccountResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => pomAccountSchema)),
    { xmlName: 'PomAccount' },
  ],
});
