/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface PortInNotificationCustomerOptInAccount {
  id?: number;
  version?: number;
  accountId?: number;
  lastModifiedDate?: string;
  new?: boolean;
}

export const portInNotificationCustomerOptInAccountSchema: Schema<PortInNotificationCustomerOptInAccount> = object(
  {
    id: ['id', optional(number())],
    version: ['version', optional(number())],
    accountId: ['accountId', optional(number()), { xmlName: 'AccountId' }],
    lastModifiedDate: ['lastModifiedDate', optional(string())],
    new: ['new', optional(boolean())],
  }
);
