/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PortInTypeEnum
 */
export enum PortInTypeEnum {
  INTERNAL = 'INTERNAL',
  AUTOMATED = 'AUTOMATED',
  AUTOMATEDOFFNET = 'AUTOMATEDOFFNET',
  MANUALOFFNET = 'MANUALOFFNET',
  MANUALTOLLFREE = 'MANUAL_TOLLFREE',
  MIXED = 'MIXED',
  MANUALONNET = 'MANUAL_ON_NET',
}

/**
 * Schema for PortInTypeEnum
 */
export const portInTypeEnumSchema: Schema<PortInTypeEnum> = stringEnum(PortInTypeEnum);
