/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PortCarrierTypeEnum
 */
export enum PortCarrierTypeEnum {
  WIRELESS = 'WIRELESS',
  WIRELINE = 'WIRELINE',
}

/**
 * Schema for PortCarrierTypeEnum
 */
export const portCarrierTypeEnumSchema: Schema<PortCarrierTypeEnum> = stringEnum(PortCarrierTypeEnum);
