/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PortOutStatus1Enum
 */
export enum PortOutStatus1Enum {
  NEW = 'NEW',
  SUPP = 'SUPP',
  MODIFY = 'MODIFY',
  COMPLETE = 'COMPLETE',
  CANCELLED = 'CANCELLED',
  VALIDATIONFAILEDNEW = 'VALIDATION_FAILED_NEW',
  VALIDATIONFAILEDSUPP = 'VALIDATION_FAILED_SUPP',
  VALIDATIONFAILEDMODIFY = 'VALIDATION_FAILED_MODIFY',
  EXCEPTION = 'EXCEPTION',
  SOAPENDING = 'SOA_PENDING',
  SOACONFLICT = 'SOA_CONFLICT',
}

/**
 * Schema for PortOutStatus1Enum
 */
export const portOutStatus1EnumSchema: Schema<PortOutStatus1Enum> = stringEnum(PortOutStatus1Enum);
