/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PreferredLanguageEnum
 */
export enum PreferredLanguageEnum {
  En = 'en',
  Fr = 'fr',
  EnumIncorrectValue = 'Incorrect value',
}

/**
 * Schema for PreferredLanguageEnum
 */
export const preferredLanguageEnumSchema: Schema<PreferredLanguageEnum> = stringEnum(PreferredLanguageEnum);
