/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface ProcessingStatusPatch {
  delete?: boolean;
}

export const processingStatusPatchSchema: Schema<ProcessingStatusPatch> = object(
  { delete: ['delete', optional(boolean()), { isAttr: true }] }
);
