/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProcessingStatus8Enum
 */
export enum ProcessingStatus8Enum {
  DRAFT = 'DRAFT',
  INPROGRESS = 'IN_PROGRESS',
  NEEDSATTENTION = 'NEEDS_ATTENTION',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

/**
 * Schema for ProcessingStatus8Enum
 */
export const processingStatus8EnumSchema: Schema<ProcessingStatus8Enum> = stringEnum(ProcessingStatus8Enum);
