/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProcessingStatus1Enum
 */
export enum ProcessingStatus1Enum {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

/**
 * Schema for ProcessingStatus1Enum
 */
export const processingStatus1EnumSchema: Schema<ProcessingStatus1Enum> = stringEnum(ProcessingStatus1Enum);
