/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProcessingStatus9Enum
 */
export enum ProcessingStatus9Enum {
  COMPLETED = 'COMPLETED',
  EXCEPTION = 'EXCEPTION',
  FOC = 'FOC',
  CANCELLED = 'CANCELLED',
}

/**
 * Schema for ProcessingStatus9Enum
 */
export const processingStatus9EnumSchema: Schema<ProcessingStatus9Enum> = stringEnum(ProcessingStatus9Enum);
