/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProcessingStatusEnum
 */
export enum ProcessingStatusEnum {
  PENDING = 'PENDING',
  RECEIVED = 'RECEIVED',
  PROCESSING = 'PROCESSING',
  COMPLETE = 'COMPLETE',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

/**
 * Schema for ProcessingStatusEnum
 */
export const processingStatusEnumSchema: Schema<ProcessingStatusEnum> = stringEnum(ProcessingStatusEnum);
