/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProcessingStatus4Enum
 */
export enum ProcessingStatus4Enum {
  DRAFT = 'DRAFT',
  PENDINGDOCUMENTS = 'PENDING_DOCUMENTS',
  SUBMITTED = 'SUBMITTED',
  REQUESTEDSUPP = 'REQUESTED_SUPP',
  FOC = 'FOC',
  COMPLETE = 'COMPLETE',
  EXCEPTION = 'EXCEPTION',
  SNAPBACK = 'SNAPBACK',
  REQUESTEDCANCEL = 'REQUESTED_CANCEL',
  CANCELLED = 'CANCELLED',
}

/**
 * Schema for ProcessingStatus4Enum
 */
export const processingStatus4EnumSchema: Schema<ProcessingStatus4Enum> = stringEnum(ProcessingStatus4Enum);
