/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ProductFeature {
  featureName?: string;
  description?: string;
}

export const productFeatureSchema: Schema<ProductFeature> = object({
  featureName: ['featureName', optional(string()), { xmlName: 'Name' }],
  description: ['description', optional(string()), { xmlName: 'Description' }],
});
