/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface ProductTnReportWrapper {
  productTnReport?: unknown;
}

export const productTnReportWrapperSchema: Schema<ProductTnReportWrapper> = object(
  { productTnReport: ['productTnReport', optional(unknown())] }
);
