/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Product, productSchema } from './product';

export interface ProductResponse {
  payload?: Product;
}

export const productResponseSchema: Schema<ProductResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => productSchema)),
    { xmlName: 'Product' },
  ],
});
