/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Product, productSchema } from './product';

export interface Products {
  products?: Product[];
}

export const productsSchema: Schema<Products> = object({
  products: [
    'products',
    optional(array(lazy(() => productSchema))),
    { xmlName: 'Product' },
  ],
});
