/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  ProductTnReportWrapper,
  productTnReportWrapperSchema,
} from './productTnReportWrapper';

export interface ProductTnHistoryResponse {
  productTnReportWrapper?: ProductTnReportWrapper;
}

export const productTnHistoryResponseSchema: Schema<ProductTnHistoryResponse> = object(
  {
    productTnReportWrapper: [
      'productTnReportWrapper',
      optional(lazy(() => productTnReportWrapperSchema)),
      { xmlName: 'ProductTNDetails' },
    ],
  }
);
