/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Protocol1Enum
 */
export enum Protocol1Enum {
  MM4 = 'MM4',
  HTTP = 'HTTP',
}

/**
 * Schema for Protocol1Enum
 */
export const protocol1EnumSchema: Schema<Protocol1Enum> = stringEnum(Protocol1Enum);
