/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface RateCenterSearchResult {
  name?: string;
  abbreviation?: string;
  availableTelephoneNumberCount?: number;
}

export const rateCenterSearchResultSchema: Schema<RateCenterSearchResult> = object(
  {
    name: ['name', optional(string()), { xmlName: 'Name' }],
    abbreviation: [
      'abbreviation',
      optional(string()),
      { xmlName: 'Abbreviation' },
    ],
    availableTelephoneNumberCount: [
      'availableTelephoneNumberCount',
      optional(number()),
      { xmlName: 'AvailableTelephoneNumberCount' },
    ],
  }
);
