/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface RateCenterSearchAndOrderType {
  rateCenterAbbreviation?: string;
  state?: string;
  quantity?: number;
}

export const rateCenterSearchAndOrderTypeSchema: Schema<RateCenterSearchAndOrderType> = object(
  {
    rateCenterAbbreviation: [
      'rateCenterAbbreviation',
      optional(string()),
      { xmlName: 'RateCenter' },
    ],
    state: ['state', optional(string()), { xmlName: 'State' }],
    quantity: ['quantity', optional(number()), { xmlName: 'Quantity' }],
  }
);
