/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface RateDeckFailedEntry {
  entryRow?: number;
  entryStringValue?: string;
  message?: string;
}

export const rateDeckFailedEntrySchema: Schema<RateDeckFailedEntry> = object({
  entryRow: ['entryRow', optional(number())],
  entryStringValue: ['entryStringValue', optional(string())],
  message: ['message', optional(string())],
});
