/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Region {
  abbreviation: string;
  name?: string;
}

export const regionSchema: Schema<Region> = object({
  abbreviation: ['abbreviation', string(), { xmlName: 'Abbreviation' }],
  name: ['name', optional(string())],
});
