/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Region, regionSchema } from './region';

export interface RegionsResponse {
  regions?: Region[];
}

export const regionsResponseSchema: Schema<RegionsResponse> = object({
  regions: [
    'regions',
    optional(array(lazy(() => regionSchema))),
    { xmlName: 'Region' },
  ],
});
