/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ReportInstanceErrorDetails,
  reportInstanceErrorDetailsSchema,
} from './reportInstanceErrorDetails';
import {
  ReportParameterValue,
  reportParameterValueSchema,
} from './reportParameterValue';

export interface ReportInstance {
  id?: number;
  reportId?: number;
  jasperId?: string;
  description?: string;
  jasperExportId?: string;
  jasperHost?: string;
  jasperSessionId?: string;
  reportName?: string;
  outputFormat?: string;
  pages?: string;
  status?: string;
  jasperOutputFormat?: string;
  requestedByUserName?: string;
  requestedForAccountId?: number;
  requestedAt?: string;
  expiresAtStr?: string;
  completedAt?: string;
  parameterValues?: ReportParameterValue[];
  errorDetails?: ReportInstanceErrorDetails;
  jasperReportStatusDisplay?: string;
  jasperExportStatusDisplay?: string;
}

export const reportInstanceSchema: Schema<ReportInstance> = object({
  id: ['id', optional(number()), { xmlName: 'Id' }],
  reportId: ['reportId', optional(number()), { xmlName: 'ReportId' }],
  jasperId: ['jasperId', optional(string()), { xmlName: 'JasperId' }],
  description: ['description', optional(string()), { xmlName: 'Description' }],
  jasperExportId: [
    'jasperExportId',
    optional(string()),
    { xmlName: 'JasperExportId' },
  ],
  jasperHost: ['jasperHost', optional(string()), { xmlName: 'JasperHost' }],
  jasperSessionId: [
    'jasperSessionId',
    optional(string()),
    { xmlName: 'JasperSessionId' },
  ],
  reportName: ['reportName', optional(string()), { xmlName: 'ReportName' }],
  outputFormat: [
    'outputFormat',
    optional(string()),
    { xmlName: 'OutputFormat' },
  ],
  pages: ['pages', optional(string()), { xmlName: 'Pages' }],
  status: ['status', optional(string()), { xmlName: 'Status' }],
  jasperOutputFormat: [
    'jasperOutputFormat',
    optional(string()),
    { xmlName: 'JasperOutputFormat' },
  ],
  requestedByUserName: [
    'requestedByUserName',
    optional(string()),
    { xmlName: 'RequestedByUserName' },
  ],
  requestedForAccountId: [
    'requestedForAccountId',
    optional(number()),
    { xmlName: 'RequestedForAccountId' },
  ],
  requestedAt: ['requestedAt', optional(string()), { xmlName: 'RequestedAt' }],
  expiresAtStr: ['expiresAtStr', optional(string()), { xmlName: 'ExpiresAt' }],
  completedAt: ['completedAt', optional(string()), { xmlName: 'CompletedAt' }],
  parameterValues: [
    'parameterValues',
    optional(
      array(
        lazy(() => reportParameterValueSchema),
        { xmlItemName: 'ParameterValue' }
      )
    ),
    { xmlName: 'Parameters' },
  ],
  errorDetails: [
    'errorDetails',
    optional(lazy(() => reportInstanceErrorDetailsSchema)),
    { xmlName: 'ErrorDetails' },
  ],
  jasperReportStatusDisplay: [
    'jasperReportStatusDisplay',
    optional(string()),
    { xmlName: 'JasperReportStatus' },
  ],
  jasperExportStatusDisplay: [
    'jasperExportStatusDisplay',
    optional(string()),
    { xmlName: 'JasperExportStatus' },
  ],
});
