/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ReportInstance, reportInstanceSchema } from './reportInstance';

export interface ReportInstanceResponse {
  payload?: ReportInstance;
}

export const reportInstanceResponseSchema: Schema<ReportInstanceResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => reportInstanceSchema)),
      { xmlName: 'Instance' },
    ],
  }
);
