/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface ReportParameterValue {
  parameterName?: string;
  jasperParameterId?: string;
  values?: string[];
}

export const reportParameterValueSchema: Schema<ReportParameterValue> = object({
  parameterName: ['parameterName', optional(string()), { xmlName: 'Name' }],
  jasperParameterId: [
    'jasperParameterId',
    optional(string()),
    { xmlName: 'JasperParameterId' },
  ],
  values: ['values', optional(array(string())), { xmlName: 'Value' }],
});
