/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Reports, reportsSchema } from './reports';

export interface ReportsResponse {
  reports?: Reports;
}

export const reportsResponseSchema: Schema<ReportsResponse> = object({
  reports: [
    'reports',
    optional(lazy(() => reportsSchema)),
    { xmlName: 'Reports' },
  ],
});
