/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface ReportInstancesResponse {
  reportInstances?: unknown;
}

export const reportInstancesResponseSchema: Schema<ReportInstancesResponse> = object(
  {
    reportInstances: [
      'reportInstances',
      optional(unknown()),
      { xmlName: 'Instances' },
    ],
  }
);
