/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Report, reportSchema } from './report';

export interface Reports {
  reports?: Report[];
}

export const reportsSchema: Schema<Reports> = object({
  reports: [
    'Reports',
    optional(array(lazy(() => reportSchema))),
    { xmlName: 'Report' },
  ],
});
