/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Report, reportSchema } from './report';

export interface ReportResponse {
  payload?: Report;
}

export const reportResponseSchema: Schema<ReportResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => reportSchema)),
    { xmlName: 'Report' },
  ],
});
