/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Reservations, reservationsSchema } from './reservations';

export interface ReservationsResponse {
  payload?: Reservations;
}

export const reservationsResponseSchema: Schema<ReservationsResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => reservationsSchema)),
    { xmlName: 'Reservations' },
  ],
});
