/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Reservation, reservationSchema } from './reservation';

export interface Reservations {
  reservations?: Reservation[];
  count?: number;
}

export const reservationsSchema: Schema<Reservations> = object({
  reservations: [
    'reservations',
    optional(array(lazy(() => reservationSchema))),
    { xmlName: 'Reservation' },
  ],
  count: ['count', optional(number()), { xmlName: 'Count' }],
});
