/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Reservation, reservationSchema } from './reservation';

export interface ReservationResponse {
  payload?: Reservation;
}

export const reservationResponseSchema: Schema<ReservationResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => reservationSchema)),
    { xmlName: 'Reservation' },
  ],
});
