/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RogerUsedForTerminationSettingsEnum
 */
export enum RogerUsedForTerminationSettingsEnum {
  False = 'false',
  Transition = 'transition',
  True = 'true',
}

/**
 * Schema for RogerUsedForTerminationSettingsEnum
 */
export const rogerUsedForTerminationSettingsEnumSchema: Schema<RogerUsedForTerminationSettingsEnum> = stringEnum(RogerUsedForTerminationSettingsEnum);
