/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  RoutingExceptionTypeEnum,
  routingExceptionTypeEnumSchema,
} from './routingExceptionTypeEnum';

export interface RoutingExceptionPrefix {
  routingExceptionType?: RoutingExceptionTypeEnum;
  prefix?: string;
}

export const routingExceptionPrefixSchema: Schema<RoutingExceptionPrefix> = object(
  {
    routingExceptionType: [
      'routingExceptionType',
      optional(routingExceptionTypeEnumSchema),
    ],
    prefix: ['prefix', optional(string())],
  }
);
