/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface SbcConfigurationPayload {
  trunkGroupId?: string;
  nodeGroupName?: string;
}

export const sbcConfigurationPayloadSchema: Schema<SbcConfigurationPayload> = object(
  {
    trunkGroupId: [
      'trunkGroupId',
      optional(string()),
      { xmlName: 'TrunkGroupId' },
    ],
    nodeGroupName: [
      'nodeGroupName',
      optional(string()),
      { xmlName: 'NodeGroupName' },
    ],
  }
);
