/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { SbcNodeGroup, sbcNodeGroupSchema } from './sbcNodeGroup';

export interface SbcNodeGroups {
  sbcNodeGroups?: SbcNodeGroup[];
}

export const sbcNodeGroupsSchema: Schema<SbcNodeGroups> = object({
  sbcNodeGroups: [
    'sbcNodeGroups',
    optional(array(lazy(() => sbcNodeGroupSchema))),
    { xmlName: 'SbcNodeGroup' },
  ],
});
