/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ScopeEnum
 */
export enum ScopeEnum {
  SYSTEM = 'SYSTEM',
  ALL = 'ALL',
  ACCOUNTADMIN = 'ACCOUNT_ADMIN',
  ACCOUNT = 'ACCOUNT',
}

/**
 * Schema for ScopeEnum
 */
export const scopeEnumSchema: Schema<ScopeEnum> = stringEnum(ScopeEnum);
