/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { IrisStatusType, irisStatusTypeSchema } from './irisStatusType';

export interface SearchError {
  code?: number;
  errorDescription?: string;
  errorType?: IrisStatusType;
}

export const searchErrorSchema: Schema<SearchError> = object({
  code: ['code', optional(number()), { xmlName: 'Code' }],
  errorDescription: [
    'errorDescription',
    optional(string()),
    { xmlName: 'Description' },
  ],
  errorType: [
    'errorType',
    optional(lazy(() => irisStatusTypeSchema)),
    { xmlName: 'IrisStatusType' },
  ],
});
