/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

export interface SettingPayload {
  settingName?: string;
  value?: unknown;
  propertyName?: string;
  stringValue?: string;
}

export const settingPayloadSchema: Schema<SettingPayload> = object({
  settingName: ['settingName', optional(string())],
  value: ['value', optional(unknown()), { xmlName: 'Value' }],
  propertyName: ['propertyName', optional(string())],
  stringValue: ['stringValue', optional(string())],
});
