/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface ShortLdapUser {
  firstName?: string;
  lastName?: string;
  userName?: string;
  email?: string;
  scope?: string;
  validated?: boolean;
  active?: boolean;
}

export const shortLdapUserSchema: Schema<ShortLdapUser> = object({
  firstName: ['firstName', optional(string()), { xmlName: 'FirstName' }],
  lastName: ['lastName', optional(string()), { xmlName: 'LastName' }],
  userName: ['userName', optional(string()), { xmlName: 'UserId' }],
  email: ['email', optional(string()), { xmlName: 'Email' }],
  scope: ['scope', optional(string()), { xmlName: 'Scope' }],
  validated: ['validated', optional(boolean()), { xmlName: 'EmailValidated' }],
  active: ['active', optional(boolean()), { xmlName: 'Active' }],
});
