/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface SipAuthDnsRecord {
  type?: TypeEnum;
  name?: string;
  data?: string;
  ttl?: number;
}

export const sipAuthDnsRecordSchema: Schema<SipAuthDnsRecord> = object({
  type: ['type', optional(typeEnumSchema), { xmlName: 'Type' }],
  name: ['name', optional(string()), { xmlName: 'Name' }],
  data: ['data', optional(string()), { xmlName: 'Data' }],
  ttl: ['ttl', optional(number()), { xmlName: 'TTL' }],
});
