/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { SipAuthDnsRecord, sipAuthDnsRecordSchema } from './sipAuthDnsRecord';
import { SipAuthSbc, sipAuthSbcSchema } from './sipAuthSbc';

export interface SipAuthSettings {
  realm?: string;
  defaultGroupName?: string;
  sbc?: SipAuthSbc;
  dnsRecords?: SipAuthDnsRecord[];
}

export const sipAuthSettingsSchema: Schema<SipAuthSettings> = object({
  realm: ['realm', optional(string()), { xmlName: 'Realm' }],
  defaultGroupName: [
    'defaultGroupName',
    optional(string()),
    { xmlName: 'DefaultGroupName' },
  ],
  sbc: ['sbc', optional(lazy(() => sipAuthSbcSchema)), { xmlName: 'SBC' }],
  dnsRecords: [
    'dnsRecords',
    optional(
      array(
        lazy(() => sipAuthDnsRecordSchema),
        { xmlItemName: 'SipAuthDnsRecord' }
      )
    ),
    { xmlName: 'DNSRecords' },
  ],
});
