/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { SipSigPort, sipSigPortSchema } from './sipSigPort';

export interface SipAuthZone {
  id?: number;
  name?: string;
  sipSigPort?: SipSigPort;
}

export const sipAuthZoneSchema: Schema<SipAuthZone> = object({
  id: ['id', optional(number()), { xmlName: 'Id' }],
  name: ['name', optional(string()), { xmlName: 'Name' }],
  sipSigPort: [
    'sipSigPort',
    optional(lazy(() => sipSigPortSchema)),
    { xmlName: 'SipSigPort' },
  ],
});
