/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { SipCredential, sipCredentialSchema } from './sipCredential';

export interface SipCredentialError {
  code?: number;
  description?: string;
  sipCredential?: SipCredential;
}

export const sipCredentialErrorSchema: Schema<SipCredentialError> = object({
  code: ['code', optional(number()), { xmlName: 'ErrorCode' }],
  description: ['description', optional(string()), { xmlName: 'Description' }],
  sipCredential: [
    'sipCredential',
    optional(lazy(() => sipCredentialSchema)),
    { xmlName: 'SipCredential' },
  ],
});
