/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  AccountSipCredentials,
  accountSipCredentialsSchema,
} from './accountSipCredentials';

export interface SipCredentials {
  accountSipCredentials?: AccountSipCredentials[];
}

export const sipCredentialsSchema: Schema<SipCredentials> = object({
  accountSipCredentials: [
    'accountSipCredentials',
    optional(array(lazy(() => accountSipCredentialsSchema))),
    { xmlName: 'SipCredentialsByAccount' },
  ],
});
