/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { SipPeerProducts, sipPeerProductsSchema } from './sipPeerProducts';

export interface SipPeerProductsResponse {
  payload?: SipPeerProducts;
}

export const sipPeerProductsResponseSchema: Schema<SipPeerProductsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerProductsSchema)),
      { xmlName: 'Products' },
    ],
  }
);
