/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  SipPeerTerminationHost,
  sipPeerTerminationHostSchema,
} from './sipPeerTerminationHost';

export interface SipPeerTerminationHosts {
  terminationHosts?: SipPeerTerminationHost[];
}

export const sipPeerTerminationHostsSchema: Schema<SipPeerTerminationHosts> = object(
  {
    terminationHosts: [
      'terminationHosts',
      optional(array(lazy(() => sipPeerTerminationHostSchema))),
      { xmlName: 'TerminationHost' },
    ],
  }
);
