/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { SipPeerHost, sipPeerHostSchema } from './sipPeerHost';

export interface SipPeerHosts {
  sipPeerHosts?: SipPeerHost[];
}

export const sipPeerHostsSchema: Schema<SipPeerHosts> = object({
  sipPeerHosts: [
    'sipPeerHosts',
    optional(array(lazy(() => sipPeerHostSchema))),
    { xmlName: 'SipPeerHost' },
  ],
});
