/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerGatewayIps1,
  sipPeerGatewayIps1Schema,
} from './sipPeerGatewayIps1';
import {
  SipPeerTerminationSettings,
  sipPeerTerminationSettingsSchema,
} from './sipPeerTerminationSettings';

export interface SipPeerTerminationProducts {
  terminationSettings?: SipPeerTerminationSettings;
  sipPeerGatewayIps?: SipPeerGatewayIps1;
}

export const sipPeerTerminationProductsSchema: Schema<SipPeerTerminationProducts> = object(
  {
    terminationSettings: [
      'terminationSettings',
      optional(lazy(() => sipPeerTerminationSettingsSchema)),
      { xmlName: 'TerminationSettings' },
    ],
    sipPeerGatewayIps: [
      'sipPeerGatewayIps',
      optional(lazy(() => sipPeerGatewayIps1Schema)),
      { xmlName: 'TerminationHosts' },
    ],
  }
);
