/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Payload4, payload4Schema } from './payload4';

export interface SipPeerGatewayIpsResponse {
  payload?: Payload4;
}

export const sipPeerGatewayIpsResponseSchema: Schema<SipPeerGatewayIpsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => payload4Schema)),
      { xmlName: 'TerminationHost' },
    ],
  }
);
