/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface SipPeerTelephoneNumbersCount {
  count?: number;
  cnamCount?: number;
  lidbCount?: number;
  dldaCount?: number;
  daCount?: number;
}

export const sipPeerTelephoneNumbersCountSchema: Schema<SipPeerTelephoneNumbersCount> = object(
  {
    count: [
      'count',
      optional(number()),
      { xmlName: 'SipPeerTelephoneNumbersCount' },
    ],
    cnamCount: [
      'cnamCount',
      optional(number()),
      { xmlName: 'CnamTelephoneNumbersCount' },
    ],
    lidbCount: [
      'lidbCount',
      optional(number()),
      { xmlName: 'LidbTelephoneNumbersCount' },
    ],
    dldaCount: [
      'dldaCount',
      optional(number()),
      { xmlName: 'DldaTelephoneNumbersCount' },
    ],
    daCount: [
      'daCount',
      optional(number()),
      { xmlName: 'DaTelephoneNumbersCount' },
    ],
  }
);
