/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema';
import {
  TerminationAttribute,
  terminationAttributeSchema,
} from './terminationAttribute';

export interface SipPeerGatewayAttribute {
  gatewayId?: number;
  attribute?: TerminationAttribute;
}

export const sipPeerGatewayAttributeSchema: Schema<SipPeerGatewayAttribute> = object(
  {
    gatewayId: ['gatewayId', optional(number()), { xmlName: 'GatewayId' }],
    attribute: [
      'attribute',
      optional(lazy(() => terminationAttributeSchema)),
      { xmlName: 'GatewayAttribute' },
    ],
  }
);
