/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerOriginationSettings,
  sipPeerOriginationSettingsSchema,
} from './sipPeerOriginationSettings';

export interface SipPeerOriginationSettingsResponse {
  payload?: SipPeerOriginationSettings;
}

export const sipPeerOriginationSettingsResponseSchema: Schema<SipPeerOriginationSettingsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerOriginationSettingsSchema)),
      { xmlName: 'SipPeerOriginationSettings' },
    ],
  }
);
