/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  SipPeerTelephoneNumber,
  sipPeerTelephoneNumberSchema,
} from './sipPeerTelephoneNumber';

export interface SipPeerTelephoneNumbers {
  sipPeerTelephoneNumbers?: SipPeerTelephoneNumber[];
}

export const sipPeerTelephoneNumbersSchema: Schema<SipPeerTelephoneNumbers> = object(
  {
    sipPeerTelephoneNumbers: [
      'sipPeerTelephoneNumbers',
      optional(array(lazy(() => sipPeerTelephoneNumberSchema))),
      { xmlName: 'SipPeerTelephoneNumber' },
    ],
  }
);
