/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface SipPeerMessagingSettings {
  breakoutCountries?: string[];
}

export const sipPeerMessagingSettingsSchema: Schema<SipPeerMessagingSettings> = object(
  {
    breakoutCountries: [
      'breakoutCountries',
      optional(array(string(), { xmlItemName: 'Country' })),
      { xmlName: 'BreakOutCountries' },
    ],
  }
);
