/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerEdgeManagementProduct,
  sipPeerEdgeManagementProductSchema,
} from './sipPeerEdgeManagementProduct';

export interface SipPeerEdgeManagementProductResponse {
  payload?: SipPeerEdgeManagementProduct;
}

export const sipPeerEdgeManagementProductResponseSchema: Schema<SipPeerEdgeManagementProductResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerEdgeManagementProductSchema)),
      { xmlName: 'EdgeManagementProduct' },
    ],
  }
);
