/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerTerminationSettings,
  sipPeerTerminationSettingsSchema,
} from './sipPeerTerminationSettings';

export interface SipPeerTerminationSettingsResponse {
  payload?: SipPeerTerminationSettings;
}

export const sipPeerTerminationSettingsResponseSchema: Schema<SipPeerTerminationSettingsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerTerminationSettingsSchema)),
      { xmlName: 'SipPeerTerminationSettings' },
    ],
  }
);
