/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerTelephoneNumberBulk,
  sipPeerTelephoneNumberBulkSchema,
} from './sipPeerTelephoneNumberBulk';

export interface SipPeerTelephoneNumberBulkResponse {
  payload?: SipPeerTelephoneNumberBulk;
}

export const sipPeerTelephoneNumberBulkResponseSchema: Schema<SipPeerTelephoneNumberBulkResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerTelephoneNumberBulkSchema)),
      { xmlName: 'SipPeerTelephoneNumberMove' },
    ],
  }
);
