/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  SipPeerSmsFeatureSettings,
  sipPeerSmsFeatureSettingsSchema,
} from './sipPeerSmsFeatureSettings';
import { SmsHost, smsHostSchema } from './smsHost';
import { SmsHttpSettings, smsHttpSettingsSchema } from './smsHttpSettings';

export interface SipPeerSmsFeature {
  sipPeerSmsFeatureSettings?: SipPeerSmsFeatureSettings;
  smsHosts?: SmsHost[];
  smsHttpSettings?: SmsHttpSettings;
}

export const sipPeerSmsFeatureSchema: Schema<SipPeerSmsFeature> = object({
  sipPeerSmsFeatureSettings: [
    'sipPeerSmsFeatureSettings',
    optional(lazy(() => sipPeerSmsFeatureSettingsSchema)),
    { xmlName: 'SipPeerSmsFeatureSettings' },
  ],
  smsHosts: [
    'smsHosts',
    optional(array(lazy(() => smsHostSchema), { xmlItemName: 'SmsHost' })),
    { xmlName: 'SmppHosts' },
  ],
  smsHttpSettings: [
    'smsHttpSettings',
    optional(lazy(() => smsHttpSettingsSchema)),
    { xmlName: 'HttpSettings' },
  ],
});
