/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SbcConfigurationPayload,
  sbcConfigurationPayloadSchema,
} from './sbcConfigurationPayload';

export interface SipPeerEdgeManagementProduct {
  sbcConfiguration?: SbcConfigurationPayload;
}

export const sipPeerEdgeManagementProductSchema: Schema<SipPeerEdgeManagementProduct> = object(
  {
    sbcConfiguration: [
      'sbcConfiguration',
      optional(lazy(() => sbcConfigurationPayloadSchema)),
      { xmlName: 'EdgeManagementSettings' },
    ],
  }
);
