/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { SipPeers, sipPeersSchema } from './sipPeers';

export interface SipPeersResponse {
  payload?: SipPeers;
}

export const sipPeersResponseSchema: Schema<SipPeersResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => sipPeersSchema)),
    { xmlName: 'SipPeers' },
  ],
});
