/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerMessagingSettings,
  sipPeerMessagingSettingsSchema,
} from './sipPeerMessagingSettings';

export interface SipPeerMessagingSettingsResponse {
  payload?: SipPeerMessagingSettings;
}

export const sipPeerMessagingSettingsResponseSchema: Schema<SipPeerMessagingSettingsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerMessagingSettingsSchema)),
      { xmlName: 'SipPeerMessagingSettings' },
    ],
  }
);
