/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SipPeerGatewayIp {
  hostName?: string;
  port?: string;
  gatewayId?: number;
}

export const sipPeerGatewayIpSchema: Schema<SipPeerGatewayIp> = object({
  hostName: ['hostName', optional(string()), { xmlName: 'HostName' }],
  port: ['port', optional(string()), { xmlName: 'Port' }],
  gatewayId: ['gatewayId', optional(number()), { xmlName: 'id' }],
});
