/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { MmsProtocols, mmsProtocolsSchema } from './mmsProtocols';
import { MmsSettings, mmsSettingsSchema } from './mmsSettings';

export interface SipPeerMmsFeature {
  mmsSettings?: MmsSettings;
  protocols?: MmsProtocols;
}

export const sipPeerMmsFeatureSchema: Schema<SipPeerMmsFeature> = object({
  mmsSettings: [
    'mmsSettings',
    optional(lazy(() => mmsSettingsSchema)),
    { xmlName: 'MmsSettings' },
  ],
  protocols: [
    'protocols',
    optional(lazy(() => mmsProtocolsSchema)),
    { xmlName: 'Protocols' },
  ],
});
