/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerGatewayAttribute,
  sipPeerGatewayAttributeSchema,
} from './sipPeerGatewayAttribute';

export interface SipPeerGatewayAttributeResponse {
  payload?: SipPeerGatewayAttribute;
}

export const sipPeerGatewayAttributeResponseSchema: Schema<SipPeerGatewayAttributeResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerGatewayAttributeSchema)),
      { xmlName: 'SipPeerGatewayAttribute' },
    ],
  }
);
