/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerTelephoneNumbersCount,
  sipPeerTelephoneNumbersCountSchema,
} from './sipPeerTelephoneNumbersCount';

export interface SipPeerTelephoneNumbersCountResponse {
  payload?: SipPeerTelephoneNumbersCount;
}

export const sipPeerTelephoneNumbersCountResponseSchema: Schema<SipPeerTelephoneNumbersCountResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerTelephoneNumbersCountSchema)),
      { xmlName: 'SipPeerTelephoneNumbersCounts' },
    ],
  }
);
