/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TelephoneNumbers2,
  telephoneNumbers2Schema,
} from './telephoneNumbers2';

export interface SipPeerTelephoneNumberBulk {
  telephoneNumbers?: TelephoneNumbers2;
}

export const sipPeerTelephoneNumberBulkSchema: Schema<SipPeerTelephoneNumberBulk> = object(
  {
    telephoneNumbers: [
      'telephoneNumbers',
      optional(lazy(() => telephoneNumbers2Schema)),
      { xmlName: 'FullNumber' },
    ],
  }
);
