/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerTerminationProducts,
  sipPeerTerminationProductsSchema,
} from './sipPeerTerminationProducts';

export interface SipPeerTerminationProductsResponse {
  payload?: SipPeerTerminationProducts;
}

export const sipPeerTerminationProductsResponseSchema: Schema<SipPeerTerminationProductsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerTerminationProductsSchema)),
      { xmlName: 'TerminationProduct' },
    ],
  }
);
