/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { SipPeer, sipPeerSchema } from './sipPeer';

export interface SipPeers {
  sipPeers?: SipPeer[];
}

export const sipPeersSchema: Schema<SipPeers> = object({
  sipPeers: [
    'sipPeers',
    optional(array(lazy(() => sipPeerSchema))),
    { xmlName: 'SipPeer' },
  ],
});
