/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface SipPeerTollFreeTotalsResponse {
  payload?: unknown;
}

export const sipPeerTollFreeTotalsResponseSchema: Schema<SipPeerTollFreeTotalsResponse> = object(
  { payload: ['payload', optional(unknown()), { xmlName: 'TollFreeTotals' }] }
);
