/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  SipPeerHttpSettings,
  sipPeerHttpSettingsSchema,
} from './sipPeerHttpSettings';

export interface SipPeerTerminationSettings {
  httpSettings?: SipPeerHttpSettings;
  voiceProtocol?: string;
}

export const sipPeerTerminationSettingsSchema: Schema<SipPeerTerminationSettings> = object(
  {
    httpSettings: [
      'httpSettings',
      optional(lazy(() => sipPeerHttpSettingsSchema)),
      { xmlName: 'HttpSettings' },
    ],
    voiceProtocol: [
      'voiceProtocol',
      optional(string()),
      { xmlName: 'VoiceProtocol' },
    ],
  }
);
