/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SipPeerGatewayAttributes,
  sipPeerGatewayAttributesSchema,
} from './sipPeerGatewayAttributes';

export interface SipPeerGatewayAttributesResponse {
  payload?: SipPeerGatewayAttributes;
}

export const sipPeerGatewayAttributesResponseSchema: Schema<SipPeerGatewayAttributesResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => sipPeerGatewayAttributesSchema)),
      { xmlName: 'SipPeerGatewayAttributes' },
    ],
  }
);
