/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { SiteBillingId, siteBillingIdSchema } from './siteBillingId';

export interface SiteBillingIdResponse {
  payload?: SiteBillingId;
}

export const siteBillingIdResponseSchema: Schema<SiteBillingIdResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => siteBillingIdSchema)),
      { xmlName: 'BillingId' },
    ],
  }
);
