/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  SiteContactPerson,
  siteContactPersonSchema,
} from './siteContactPerson';
import {
  SiteSalesRepresentative,
  siteSalesRepresentativeSchema,
} from './siteSalesRepresentative';

export interface SiteContract {
  salesRepresentative?: SiteSalesRepresentative;
  contactPerson?: SiteContactPerson;
}

export const siteContractSchema: Schema<SiteContract> = object({
  salesRepresentative: [
    'salesRepresentative',
    optional(lazy(() => siteSalesRepresentativeSchema)),
    { xmlName: 'SalesRepresentative' },
  ],
  contactPerson: [
    'contactPerson',
    optional(lazy(() => siteContactPersonSchema)),
    { xmlName: 'ContactPerson' },
  ],
});
