/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface SiteUcTrunkingConfigurationPayload {
  type?: string;
  usageCategory?: string;
}

export const siteUcTrunkingConfigurationPayloadSchema: Schema<SiteUcTrunkingConfigurationPayload> = object(
  {
    type: ['type', optional(string()), { xmlName: 'Type' }],
    usageCategory: [
      'usageCategory',
      optional(string()),
      { xmlName: 'UsageCategory' },
    ],
  }
);
