/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { SiteContract, siteContractSchema } from './siteContract';

export interface SiteContractResponse {
  payload?: SiteContract;
}

export const siteContractResponseSchema: Schema<SiteContractResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => siteContractSchema)),
    { xmlName: 'Contract' },
  ],
});
