/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface SiteSalesRepresentative {
  id?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phoneNumber?: string;
}

export const siteSalesRepresentativeSchema: Schema<SiteSalesRepresentative> = object(
  {
    id: ['id', optional(string()), { xmlName: 'Id' }],
    firstName: ['firstName', optional(string()), { xmlName: 'FirstName' }],
    lastName: ['lastName', optional(string()), { xmlName: 'LastName' }],
    email: ['email', optional(string()), { xmlName: 'Email' }],
    phoneNumber: [
      'phoneNumber',
      optional(string()),
      { xmlName: 'PhoneNumber' },
    ],
  }
);
