/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Site, siteSchema } from './site';

export interface Sites {
  sites?: Site[];
}

export const sitesSchema: Schema<Sites> = object({
  sites: [
    'sites',
    optional(array(lazy(() => siteSchema))),
    { xmlName: 'Site' },
  ],
});
