/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface SiteTnTotal {
  totalTnCount?: number;
}

export const siteTnTotalSchema: Schema<SiteTnTotal> = object({
  totalTnCount: ['totalTnCount', optional(number()), { xmlName: 'TotalCount' }],
});
