/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema';
import { SipPeerHosts, sipPeerHostsSchema } from './sipPeerHosts';

export interface SiteHost {
  siteId?: number;
  sipPeerHosts?: SipPeerHosts;
}

export const siteHostSchema: Schema<SiteHost> = object({
  siteId: ['siteId', optional(number()), { xmlName: 'SiteId' }],
  sipPeerHosts: [
    'sipPeerHosts',
    optional(lazy(() => sipPeerHostsSchema)),
    { xmlName: 'SipPeerHosts' },
  ],
});
