/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { SiteLock, siteLockSchema } from './siteLock';

export interface SiteLockResponse {
  payload?: SiteLock;
}

export const siteLockResponseSchema: Schema<SiteLockResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => siteLockSchema)),
    { xmlName: 'Lock' },
  ],
});
