/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Sites, sitesSchema } from './sites';

export interface SitesResponse {
  payload?: Sites;
}

export const sitesResponseSchema: Schema<SitesResponse> = object({
  payload: ['payload', optional(lazy(() => sitesSchema)), { xmlName: 'Sites' }],
});
