/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SlingshotEnv {
  sippeerId?: number;
  value?: string;
}

export const slingshotEnvSchema: Schema<SlingshotEnv> = object({
  sippeerId: ['sippeerId', optional(number()), { xmlName: 'SipPeerId' }],
  value: ['value', optional(string()), { xmlName: 'Value' }],
});
