/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface SmsHosts {
  empty?: boolean;
}

export const smsHostsSchema: Schema<SmsHosts> = object({
  empty: ['empty', optional(boolean())],
});
