/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import {
  ConnectionTypeEnum,
  connectionTypeEnumSchema,
} from './connectionTypeEnum';

export interface SmsHost {
  hostName?: string;
  port?: string;
  hostId?: number;
  priority?: number;
  username?: string;
  password?: string;
  connectionType?: ConnectionTypeEnum;
}

export const smsHostSchema: Schema<SmsHost> = object({
  hostName: ['hostName', optional(string()), { xmlName: 'HostName' }],
  port: ['port', optional(string()), { xmlName: 'Port' }],
  hostId: ['hostId', optional(number()), { xmlName: 'HostId' }],
  priority: ['priority', optional(number()), { xmlName: 'Priority' }],
  username: ['username', optional(string()), { xmlName: 'Username' }],
  password: ['password', optional(string()), { xmlName: 'Password' }],
  connectionType: [
    'connectionType',
    optional(connectionTypeEnumSchema),
    { xmlName: 'ConnectionType' },
  ],
});
