/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status3Enum
 */
export enum Status3Enum {
  RECEIVED = 'RECEIVED',
  PROCESSING = 'PROCESSING',
  ACTIONREQUIRED = 'ACTION_REQUIRED',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED',
  REQUESTEDCANCEL = 'REQUESTED_CANCEL',
  CANCELLED = 'CANCELLED',
}

/**
 * Schema for Status3Enum
 */
export const status3EnumSchema: Schema<Status3Enum> = stringEnum(Status3Enum);
