/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status1Enum
 */
export enum Status1Enum {
  MIGRATED = 'MIGRATED',
  ROLLEDBACK = 'ROLLEDBACK',
}

/**
 * Schema for Status1Enum
 */
export const status1EnumSchema: Schema<Status1Enum> = stringEnum(Status1Enum);
