/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status7Enum
 */
export enum Status7Enum {
  PROCESSING = 'PROCESSING',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED',
}

/**
 * Schema for Status7Enum
 */
export const status7EnumSchema: Schema<Status7Enum> = stringEnum(Status7Enum);
