/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface StateSearchAndOrderType {
  quantity?: number;
  state?: string;
}

export const stateSearchAndOrderTypeSchema: Schema<StateSearchAndOrderType> = object(
  {
    quantity: ['quantity', optional(number()), { xmlName: 'Quantity' }],
    state: ['state', optional(string()), { xmlName: 'State' }],
  }
);
