/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Subscription, subscriptionSchema } from './subscription';

export interface SubscriptionResponse {
  payload?: Subscription;
}

export const subscriptionResponseSchema: Schema<SubscriptionResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => subscriptionSchema)),
    { xmlName: 'Subscription' },
  ],
});
