/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubscriberType1Enum
 */
export enum SubscriberType1Enum {
  Business = 'business',
  Residential = 'residential',
  Generic = 'generic',
}

/**
 * Schema for SubscriberType1Enum
 */
export const subscriberType1EnumSchema: Schema<SubscriberType1Enum> = stringEnum(SubscriberType1Enum);
