/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubscriberTypeEnum
 */
export enum SubscriberTypeEnum {
  BUSINESS = 'BUSINESS',
  RESIDENTIAL = 'RESIDENTIAL',
}

/**
 * Schema for SubscriberTypeEnum
 */
export const subscriberTypeEnumSchema: Schema<SubscriberTypeEnum> = stringEnum(SubscriberTypeEnum);
