/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SupplementalEnum
 */
export enum SupplementalEnum {
  NONE = 'NONE',
  CANCEL = 'CANCEL',
  UPDATE = 'UPDATE',
  OTHER = 'OTHER',
}

/**
 * Schema for SupplementalEnum
 */
export const supplementalEnumSchema: Schema<SupplementalEnum> = stringEnum(SupplementalEnum);
