/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SystemEventSubscription {
  id?: number;
  systemEvent?: string;
  email?: string;
  zendeskGroupId?: string;
  digestType?: string;
  callbackOrderType?: string;
}

export const systemEventSubscriptionSchema: Schema<SystemEventSubscription> = object(
  {
    id: ['id', optional(number()), { xmlName: 'SubscriptionId' }],
    systemEvent: [
      'systemEvent',
      optional(string()),
      { xmlName: 'SystemEvent' },
    ],
    email: ['email', optional(string()), { xmlName: 'Email' }],
    zendeskGroupId: [
      'zendeskGroupId',
      optional(string()),
      { xmlName: 'ZendeskGroupId' },
    ],
    digestType: ['digestType', optional(string()), { xmlName: 'DigestType' }],
    callbackOrderType: [
      'callbackOrderType',
      optional(string()),
      { xmlName: 'CallbackOrderType' },
    ],
  }
);
