/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface TelephoneNumberGroupError {
  code?: number;
  description?: string;
  telephoneNumbers?: string[];
}

export const telephoneNumberGroupErrorSchema: Schema<TelephoneNumberGroupError> = object(
  {
    code: ['code', optional(number()), { xmlName: 'Code' }],
    description: [
      'description',
      optional(string()),
      { xmlName: 'Description' },
    ],
    telephoneNumbers: [
      'telephoneNumbers',
      optional(array(string(), { xmlItemName: 'TelephoneNumber' })),
      { xmlName: 'TelephoneNumbers' },
    ],
  }
);
