/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TelephoneNumberDetailHistoryPayload,
  telephoneNumberDetailHistoryPayloadSchema,
} from './telephoneNumberDetailHistoryPayload';

export interface TelephoneNumberDetailHistoryResponse {
  payload?: TelephoneNumberDetailHistoryPayload;
}

export const telephoneNumberDetailHistoryResponseSchema: Schema<TelephoneNumberDetailHistoryResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => telephoneNumberDetailHistoryPayloadSchema)),
      { xmlName: 'TelephoneNumberDetails' },
    ],
  }
);
