/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DetailedTelephoneNumberStatus,
  detailedTelephoneNumberStatusSchema,
} from './detailedTelephoneNumberStatus';
import {
  OrderDetailsReport,
  orderDetailsReportSchema,
} from './orderDetailsReport';

export interface TelephoneNumberStatusWrapper {
  telephoneNumberStatusList?: DetailedTelephoneNumberStatus[];
  telephoneNumber?: string;
  tnStatus?: string;
  lastModifiedDateInUtc?: string;
  orderCreatedDateInUtc?: string;
  orderId?: string;
  orderType?: string;
  inServiceDate?: string;
  siteId?: number;
  peerGroup?: string;
  accountId?: number;
  tnDetails?: OrderDetailsReport;
}

export const telephoneNumberStatusWrapperSchema: Schema<TelephoneNumberStatusWrapper> = object(
  {
    telephoneNumberStatusList: [
      'telephoneNumberStatusList',
      optional(
        array(
          lazy(() => detailedTelephoneNumberStatusSchema),
          { xmlItemName: 'DetailedTelephoneNumberStatus' }
        )
      ),
      { xmlName: 'TelephoneNumberStatuses' },
    ],
    telephoneNumber: [
      'telephoneNumber',
      optional(string()),
      { xmlName: 'TelephoneNumber' },
    ],
    tnStatus: ['tnStatus', optional(string()), { xmlName: 'Status' }],
    lastModifiedDateInUtc: [
      'lastModifiedDateInUtc',
      optional(string()),
      { xmlName: 'LastModifiedDate' },
    ],
    orderCreatedDateInUtc: [
      'orderCreatedDateInUtc',
      optional(string()),
      { xmlName: 'OrderCreateDate' },
    ],
    orderId: ['orderId', optional(string()), { xmlName: 'OrderId' }],
    orderType: ['orderType', optional(string()), { xmlName: 'OrderType' }],
    inServiceDate: [
      'inServiceDate',
      optional(string()),
      { xmlName: 'InServiceDate' },
    ],
    siteId: ['siteId', optional(number()), { xmlName: 'SiteId' }],
    peerGroup: ['peerGroup', optional(string()), { xmlName: 'PeerGroup' }],
    accountId: ['accountId', optional(number()), { xmlName: 'AccountId' }],
    tnDetails: [
      'tnDetails',
      optional(lazy(() => orderDetailsReportSchema)),
      { xmlName: 'TelephoneNumberDetails' },
    ],
  }
);
