/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface TelephoneNumberDetail {
  telephoneNumber?: string;
  rateCenterAbbreviation?: string;
  lata?: string;
  city?: string;
  state?: string;
  vendorName?: string;
  vendorId?: number;
  tier?: number;
  isTollFree?: boolean;
}

export const telephoneNumberDetailSchema: Schema<TelephoneNumberDetail> = object(
  {
    telephoneNumber: [
      'telephoneNumber',
      optional(string()),
      { xmlName: 'FullNumber' },
    ],
    rateCenterAbbreviation: [
      'rateCenterAbbreviation',
      optional(string()),
      { xmlName: 'RateCenter' },
    ],
    lata: ['lata', optional(string()), { xmlName: 'LATA' }],
    city: ['city', optional(string()), { xmlName: 'City' }],
    state: ['state', optional(string()), { xmlName: 'State' }],
    vendorName: ['vendorName', optional(string()), { xmlName: 'VendorName' }],
    vendorId: ['vendorId', optional(number()), { xmlName: 'VendorId' }],
    tier: ['tier', optional(number()), { xmlName: 'Tier' }],
    isTollFree: ['isTollFree', optional(boolean()), { xmlName: 'isTollfree' }],
  }
);
