/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  TelephoneNumbersDetail,
  telephoneNumbersDetailSchema,
} from './telephoneNumbersDetail';

export interface TelephoneNumbersDetailsHistory {
  telephoneNumbersDetails?: TelephoneNumbersDetail[];
}

export const telephoneNumbersDetailsHistorySchema: Schema<TelephoneNumbersDetailsHistory> = object(
  {
    telephoneNumbersDetails: [
      'telephoneNumbersDetails',
      optional(array(lazy(() => telephoneNumbersDetailSchema))),
      { xmlName: 'TNs' },
    ],
  }
);
