/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  unknown,
} from '../schema';
import { PaginationLinks, paginationLinksSchema } from './paginationLinks';
import {
  TelephoneNumberGroupError,
  telephoneNumberGroupErrorSchema,
} from './telephoneNumberGroupError';

export interface TelephoneNumbersHistoryResponse {
  payload?: unknown;
  paginationLinks?: PaginationLinks;
  telephoneNumberCount?: number;
  errorList?: TelephoneNumberGroupError[];
}

export const telephoneNumbersHistoryResponseSchema: Schema<TelephoneNumbersHistoryResponse> = object(
  {
    payload: ['payload', optional(unknown()), { xmlName: 'TelephoneNumbers' }],
    paginationLinks: [
      'paginationLinks',
      optional(lazy(() => paginationLinksSchema)),
      { xmlName: 'Links' },
    ],
    telephoneNumberCount: [
      'telephoneNumberCount',
      optional(number()),
      { xmlName: 'TelephoneNumberCount' },
    ],
    errorList: [
      'errorList',
      optional(
        array(
          lazy(() => telephoneNumberGroupErrorSchema),
          { xmlItemName: 'Error' }
        )
      ),
      { xmlName: 'ErrorList' },
    ],
  }
);
