/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema';
import {
  AllInternationalNumbers,
  allInternationalNumbersSchema,
} from './allInternationalNumbers';
import { AllNanpNumbers, allNanpNumbersSchema } from './allNanpNumbers';
import { AllShortCodes, allShortCodesSchema } from './allShortCodes';

export interface TelephoneNumbers1 {
  allShortCode?: boolean;
  anyNanp?: boolean;
  anyShortCode?: boolean;
  allNanp?: boolean;
  allInternational?: boolean;
  anyInternational?: boolean;
  allNanpNumbers?: AllNanpNumbers;
  allInternationalNumbers?: AllInternationalNumbers;
  allShortCodes?: AllShortCodes;
  empty?: boolean;
}

export const telephoneNumbers1Schema: Schema<TelephoneNumbers1> = object({
  allShortCode: ['allShortCode', optional(boolean())],
  anyNanp: ['anyNanp', optional(boolean())],
  anyShortCode: ['anyShortCode', optional(boolean())],
  allNanp: ['allNanp', optional(boolean())],
  allInternational: ['allInternational', optional(boolean())],
  anyInternational: ['anyInternational', optional(boolean())],
  allNanpNumbers: [
    'allNanpNumbers',
    optional(lazy(() => allNanpNumbersSchema)),
    { xmlName: 'AllNanpNumbers' },
  ],
  allInternationalNumbers: [
    'allInternationalNumbers',
    optional(lazy(() => allInternationalNumbersSchema)),
    { xmlName: 'AllInternationalNumbers' },
  ],
  allShortCodes: [
    'allShortCodes',
    optional(lazy(() => allShortCodesSchema)),
    { xmlName: 'AllShortCodes' },
  ],
  empty: ['empty', optional(boolean())],
});
