/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TelephoneNumberAvailableNnRoutes,
  telephoneNumberAvailableNnRoutesSchema,
} from './telephoneNumberAvailableNnRoutes';

export interface TelephoneNumberAvailableNnRoutesResponse {
  payload?: TelephoneNumberAvailableNnRoutes;
}

export const telephoneNumberAvailableNnRoutesResponseSchema: Schema<TelephoneNumberAvailableNnRoutesResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => telephoneNumberAvailableNnRoutesSchema)),
      { xmlName: 'AvailableNnRoutes' },
    ],
  }
);
