/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface TelephoneNumbersPayload {
  telephoneNumbers?: string[];
}

export const telephoneNumbersPayloadSchema: Schema<TelephoneNumbersPayload> = object(
  {
    telephoneNumbers: [
      'telephoneNumbers',
      optional(array(string())),
      { xmlName: 'Tn' },
    ],
  }
);
