/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { TnDetailsNnRoute, tnDetailsNnRouteSchema } from './tnDetailsNnRoute';

export interface TelephoneNumberAvailableNnRoutes {
  tnDetailsNnRoutes?: TnDetailsNnRoute[];
}

export const telephoneNumberAvailableNnRoutesSchema: Schema<TelephoneNumberAvailableNnRoutes> = object(
  {
    tnDetailsNnRoutes: [
      'tnDetailsNnRoutes',
      optional(array(lazy(() => tnDetailsNnRouteSchema))),
      { xmlName: 'NNRoute' },
    ],
  }
);
