/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { PaginationLinks, paginationLinksSchema } from './paginationLinks';

export interface TelephoneNumberListWrapper {
  totalCount?: number;
  paginationLinks?: PaginationLinks;
  count?: number;
  telephoneNumberList?: string[];
  errorMessage?: string;
}

export const telephoneNumberListWrapperSchema: Schema<TelephoneNumberListWrapper> = object(
  {
    totalCount: ['totalCount', optional(number()), { xmlName: 'TotalCount' }],
    paginationLinks: [
      'paginationLinks',
      optional(lazy(() => paginationLinksSchema)),
      { xmlName: 'Links' },
    ],
    count: ['count', optional(number()), { xmlName: 'Count' }],
    telephoneNumberList: [
      'telephoneNumberList',
      optional(array(string())),
      { xmlName: 'TelephoneNumber' },
    ],
    errorMessage: [
      'errorMessage',
      optional(string()),
      { xmlName: 'ErrorMessage' },
    ],
  }
);
