/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { DeckTypeEnum, deckTypeEnumSchema } from './deckTypeEnum';
import {
  RateDeckFailedEntry,
  rateDeckFailedEntrySchema,
} from './rateDeckFailedEntry';

export interface TerminationRateDeckMetadata {
  rogerDeckId?: number;
  name?: string;
  deckType?: DeckTypeEnum;
  rows?: number;
  fileName?: string;
  failedEntries?: RateDeckFailedEntry[];
}

export const terminationRateDeckMetadataSchema: Schema<TerminationRateDeckMetadata> = object(
  {
    rogerDeckId: ['rogerDeckId', optional(number())],
    name: ['name', optional(string())],
    deckType: ['deckType', optional(deckTypeEnumSchema)],
    rows: ['rows', optional(number())],
    fileName: ['fileName', optional(string())],
    failedEntries: [
      'failedEntries',
      optional(
        array(
          lazy(() => rateDeckFailedEntrySchema),
          { xmlItemName: 'RateDeckFailedEntry' }
        )
      ),
    ],
  }
);
