/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationRateDeckWrapper,
  terminationRateDeckWrapperSchema,
} from './terminationRateDeckWrapper';

export interface TerminationRateDeckResponse {
  payload?: TerminationRateDeckWrapper;
}

export const terminationRateDeckResponseSchema: Schema<TerminationRateDeckResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationRateDeckWrapperSchema)),
      { xmlName: 'TerminationRateDeckWrapper' },
    ],
  }
);
