/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationRateDeckMetadata,
  terminationRateDeckMetadataSchema,
} from './terminationRateDeckMetadata';

export interface TerminationRateDeckMetadataResponse {
  payload?: TerminationRateDeckMetadata;
}

export const terminationRateDeckMetadataResponseSchema: Schema<TerminationRateDeckMetadataResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationRateDeckMetadataSchema)),
      { xmlName: 'TerminationRateDeckMetadata' },
    ],
  }
);
