/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Payload10, payload10Schema } from './payload10';

export interface TerminationAttributeMetadataByOriginResponse {
  payload?: Payload10;
}

export const terminationAttributeMetadataByOriginResponseSchema: Schema<TerminationAttributeMetadataByOriginResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => payload10Schema)),
      { xmlName: 'TerminationAttributeMetadatas' },
    ],
  }
);
