/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Payload12, payload12Schema } from './payload12';

export interface TerminationCarrierMasksResponse {
  payload?: Payload12;
}

export const terminationCarrierMasksResponseSchema: Schema<TerminationCarrierMasksResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => payload12Schema)),
      { xmlName: 'TerminationCarrierMasks' },
    ],
  }
);
