/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationRoutingExceptionFile,
  terminationRoutingExceptionFileSchema,
} from './terminationRoutingExceptionFile';

export interface TerminationRoutingExceptionFileResponse {
  payload?: TerminationRoutingExceptionFile;
}

export const terminationRoutingExceptionFileResponseSchema: Schema<TerminationRoutingExceptionFileResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationRoutingExceptionFileSchema)),
      { xmlName: 'TerminationRoutingExceptionFile' },
    ],
  }
);
