/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationGateway,
  terminationGatewaySchema,
} from './terminationGateway';

export interface TerminationGatewayAttributeResponse {
  payload?: TerminationGateway;
}

export const terminationGatewayAttributeResponseSchema: Schema<TerminationGatewayAttributeResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationGatewaySchema)),
      { xmlName: 'TerminationGateway' },
    ],
  }
);
