/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Payload18, payload18Schema } from './payload18';

export interface TerminationGatewaysResponse {
  payload?: Payload18;
}

export const terminationGatewaysResponseSchema: Schema<TerminationGatewaysResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => payload18Schema)),
      { xmlName: 'TerminationGateways' },
    ],
  }
);
