/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface TerminationListTerminationRateDeckMetadata {
  empty?: boolean;
}

export const terminationListTerminationRateDeckMetadataSchema: Schema<TerminationListTerminationRateDeckMetadata> = object(
  { empty: ['empty', optional(boolean())] }
);
