/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationProductWrapper,
  terminationProductWrapperSchema,
} from './terminationProductWrapper';

export interface TerminationCustomerProductAssignmentResponse {
  payload?: TerminationProductWrapper;
}

export const terminationCustomerProductAssignmentResponseSchema: Schema<TerminationCustomerProductAssignmentResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationProductWrapperSchema)),
      { xmlName: 'TerminationProductWrapper' },
    ],
  }
);
