/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface TerminationRoutingExceptionFile {
  id?: number;
  routingExceptionName?: string;
  fileName?: string;
  fileBytes?: string[];
}

export const terminationRoutingExceptionFileSchema: Schema<TerminationRoutingExceptionFile> = object(
  {
    id: ['id', optional(number())],
    routingExceptionName: ['routingExceptionName', optional(string())],
    fileName: ['fileName', optional(string())],
    fileBytes: ['fileBytes', optional(array(string()))],
  }
);
