/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface TerminationListTerminationCarrier {
  empty?: boolean;
}

export const terminationListTerminationCarrierSchema: Schema<TerminationListTerminationCarrier> = object(
  { empty: ['empty', optional(boolean())] }
);
