/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface TerminationMigrationWrapper {
  accountId?: number;
}

export const terminationMigrationWrapperSchema: Schema<TerminationMigrationWrapper> = object(
  { accountId: ['accountId', optional(number())] }
);
