/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationProduct,
  terminationProductSchema,
} from './terminationProduct';
import {
  TerminationProductAssignment,
  terminationProductAssignmentSchema,
} from './terminationProductAssignment';

export interface TerminationProductWrapper {
  terminationProduct?: TerminationProduct;
  terminationProductAssignment?: TerminationProductAssignment;
}

export const terminationProductWrapperSchema: Schema<TerminationProductWrapper> = object(
  {
    terminationProduct: [
      'terminationProduct',
      optional(lazy(() => terminationProductSchema)),
      { xmlName: 'TerminationProduct' },
    ],
    terminationProductAssignment: [
      'terminationProductAssignment',
      optional(lazy(() => terminationProductAssignmentSchema)),
      { xmlName: 'TerminationProductAssignment' },
    ],
  }
);
