/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationAttributeMetadata,
  terminationAttributeMetadataSchema,
} from './terminationAttributeMetadata';

export interface TerminationAttributeMetadataByNameResponse {
  payload?: TerminationAttributeMetadata;
}

export const terminationAttributeMetadataByNameResponseSchema: Schema<TerminationAttributeMetadataByNameResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationAttributeMetadataSchema)),
      { xmlName: 'TerminationAttributeMetadata' },
    ],
  }
);
