/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TerminationRateDeckAssignment {
  id?: number;
  termServiceRateDeckId?: number;
  termServiceAccountId?: number;
  externalProfileId?: number;
  externalAssignmentId?: number;
  billingAccountId?: number;
  increaseDate?: string;
  decreaseDate?: string;
}

export const terminationRateDeckAssignmentSchema: Schema<TerminationRateDeckAssignment> = object(
  {
    id: ['id', optional(number())],
    termServiceRateDeckId: ['termServiceRateDeckId', optional(number())],
    termServiceAccountId: ['termServiceAccountId', optional(number())],
    externalProfileId: ['externalProfileId', optional(number())],
    externalAssignmentId: ['externalAssignmentId', optional(number())],
    billingAccountId: ['billingAccountId', optional(number())],
    increaseDate: ['increaseDate', optional(string())],
    decreaseDate: ['decreaseDate', optional(string())],
  }
);
