/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import { DeckFileTypeEnum, deckFileTypeEnumSchema } from './deckFileTypeEnum';

export interface TerminationRateDeck {
  deckByteBuffer?: string[];
  deckFileType?: DeckFileTypeEnum;
}

export const terminationRateDeckSchema: Schema<TerminationRateDeck> = object({
  deckByteBuffer: ['deckByteBuffer', optional(array(string()))],
  deckFileType: ['deckFileType', optional(deckFileTypeEnumSchema)],
});
