/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Payload9, payload9Schema } from './payload9';

export interface TerminationRateDeckAssignmentsUtilityResponse {
  payload?: Payload9;
}

export const terminationRateDeckAssignmentsUtilityResponseSchema: Schema<TerminationRateDeckAssignmentsUtilityResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => payload9Schema)),
      { xmlName: 'Payload9' },
    ],
  }
);
