/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Payload7, payload7Schema } from './payload7';

export interface TerminationRateDeckMetadatasResponse {
  payload?: Payload7;
}

export const terminationRateDeckMetadatasResponseSchema: Schema<TerminationRateDeckMetadatasResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => payload7Schema)),
      { xmlName: 'terminationRateDeckMetadatas' },
    ],
  }
);
