/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationAccount,
  terminationAccountSchema,
} from './terminationAccount';

export interface TerminationAccountResponse {
  payload?: TerminationAccount;
}

export const terminationAccountResponseSchema: Schema<TerminationAccountResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationAccountSchema)),
      { xmlName: 'TerminationAccount' },
    ],
  }
);
