/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { dict, number, object, optional, Schema, string } from '../schema';

export interface TerminationProductAssignment {
  attributeId?: number;
  productName?: string;
  attributes?: Record<string, string>;
}

export const terminationProductAssignmentSchema: Schema<TerminationProductAssignment> = object(
  {
    attributeId: ['attributeId', optional(number())],
    productName: ['productName', optional(string())],
    attributes: ['attributes', optional(dict(string()))],
  }
);
