/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationCarrierMask,
  terminationCarrierMaskSchema,
} from './terminationCarrierMask';

export interface TerminationCarrierMaskMetadataResponse {
  payload?: TerminationCarrierMask;
}

export const terminationCarrierMaskMetadataResponseSchema: Schema<TerminationCarrierMaskMetadataResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationCarrierMaskSchema)),
      { xmlName: 'TerminationCarrierMask' },
    ],
  }
);
