/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface TerminationAttribute {
  id?: number;
  type?: string;
  value?: string;
  profileId?: number;
  effectiveDate?: string;
  inEffectiveDate?: string;
  externalId?: number;
  productId?: number;
  productAttributeId?: number;
  isTemplate?: boolean;
}

export const terminationAttributeSchema: Schema<TerminationAttribute> = object({
  id: ['id', optional(number())],
  type: ['type', optional(string())],
  value: ['value', optional(string())],
  profileId: ['profileId', optional(number())],
  effectiveDate: ['effectiveDate', optional(string())],
  inEffectiveDate: ['inEffectiveDate', optional(string())],
  externalId: ['externalId', optional(number())],
  productId: ['productId', optional(number())],
  productAttributeId: ['productAttributeId', optional(number())],
  isTemplate: ['isTemplate', optional(boolean())],
});
