/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TerminationMigrationWrapper,
  terminationMigrationWrapperSchema,
} from './terminationMigrationWrapper';

export interface TerminationMigrationResponse {
  payload?: TerminationMigrationWrapper;
}

export const terminationMigrationResponseSchema: Schema<TerminationMigrationResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => terminationMigrationWrapperSchema)),
      { xmlName: 'TerminationMigrationWrapper' },
    ],
  }
);
