/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Payload6, payload6Schema } from './payload6';

export interface TerminationCarriersResponse {
  payload?: Payload6;
}

export const terminationCarriersResponseSchema: Schema<TerminationCarriersResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => payload6Schema)),
      { xmlName: 'TerminationCarriers' },
    ],
  }
);
