/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TnActivationStatus,
  tnActivationStatusSchema,
} from './tnActivationStatus';

export interface TnActivationStatusResponse {
  payload?: TnActivationStatus;
}

export const tnActivationStatusResponseSchema: Schema<TnActivationStatusResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => tnActivationStatusSchema)),
      { xmlName: 'ActivationStatus' },
    ],
  }
);
