/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TnE911Address {
  name?: string;
  houseNo?: string;
  streetName?: string;
  addressLine2?: string;
  city?: string;
  stateCode?: string;
  zip?: string;
  zip4?: string;
}

export const tnE911AddressSchema: Schema<TnE911Address> = object({
  name: ['name', optional(string()), { xmlName: 'Name' }],
  houseNo: ['houseNo', optional(string()), { xmlName: 'HouseNumber' }],
  streetName: ['streetName', optional(string()), { xmlName: 'StreetName' }],
  addressLine2: [
    'addressLine2',
    optional(string()),
    { xmlName: 'AddressLine2' },
  ],
  city: ['city', optional(string()), { xmlName: 'City' }],
  stateCode: ['stateCode', optional(string()), { xmlName: 'StateCode' }],
  zip: ['zip', optional(string()), { xmlName: 'Zip' }],
  zip4: ['zip4', optional(string()), { xmlName: 'PlusFour' }],
});
