/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface TnHistoryRecast {
  tag?: string;
  accountIds?: number[];
  fullnumbers?: string[];
}

export const tnHistoryRecastSchema: Schema<TnHistoryRecast> = object({
  tag: ['tag', optional(string()), { xmlName: 'Tag' }],
  accountIds: [
    'accountIds',
    optional(array(number(), { xmlItemName: 'AccountId' })),
    { xmlName: 'AccountIds' },
  ],
  fullnumbers: [
    'fullnumbers',
    optional(array(string(), { xmlItemName: 'TelephoneNumber' })),
    { xmlName: 'TelephoneNumbers' },
  ],
});
