/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TnPortOutPasscodePayload {
  fullNumber?: string;
  passcode?: string;
}

export const tnPortOutPasscodePayloadSchema: Schema<TnPortOutPasscodePayload> = object(
  {
    fullNumber: ['fullNumber', optional(string()), { xmlName: 'FullNumber' }],
    passcode: ['passcode', optional(string()), { xmlName: 'Passcode' }],
  }
);
