/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AddressErrorDescription,
  addressErrorDescriptionSchema,
} from './addressErrorDescription';
import { TnSipPeer, tnSipPeerSchema } from './tnSipPeer';

export interface TnSipPeerResponse {
  payload?: TnSipPeer;
  addressErrorDescription?: AddressErrorDescription;
}

export const tnSipPeerResponseSchema: Schema<TnSipPeerResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => tnSipPeerSchema)),
    { xmlName: 'SipPeer' },
  ],
  addressErrorDescription: [
    'addressErrorDescription',
    optional(lazy(() => addressErrorDescriptionSchema)),
    { xmlName: 'AddressErrorDescription' },
  ],
});
