/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TnTypePayload {
  id?: number;
  source?: string;
  tnType?: string;
}

export const tnTypePayloadSchema: Schema<TnTypePayload> = object({
  id: ['id', optional(number()), { xmlName: 'TnTypeId' }],
  source: ['source', optional(string()), { xmlName: 'Source' }],
  tnType: ['tnType', optional(string()), { xmlName: 'Type' }],
});
