/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { TokenGroups, tokenGroupsSchema } from './tokenGroups';

export interface TokensResponse {
  payload?: TokenGroups;
}

export const tokensResponseSchema: Schema<TokensResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => tokenGroupsSchema)),
    { xmlName: 'TokenGroups' },
  ],
});
