/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { TokenGroup, tokenGroupSchema } from './tokenGroup';

export interface TokenGroups {
  tokenGroups?: TokenGroup[];
}

export const tokenGroupsSchema: Schema<TokenGroups> = object({
  tokenGroups: [
    'tokenGroups',
    optional(array(lazy(() => tokenGroupSchema))),
    { xmlName: 'TokenGroup' },
  ],
});
