/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface TokenScope {
  accountId?: number;
}

export const tokenScopeSchema: Schema<TokenScope> = object({
  accountId: ['accountId', optional(number()), { xmlName: 'AccountScope' }],
});
