/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ApiToken, apiTokenSchema } from './apiToken';

export interface TokenResponse {
  payload?: ApiToken;
}

export const tokenResponseSchema: Schema<TokenResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => apiTokenSchema)),
    { xmlName: 'ApiToken' },
  ],
});
