/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { TokenScope, tokenScopeSchema } from './tokenScope';

export interface TokenGroup {
  tokens?: string[];
  tokenScope?: TokenScope;
}

export const tokenGroupSchema: Schema<TokenGroup> = object({
  tokens: [
    'tokens',
    optional(array(string(), { xmlItemName: 'Token' })),
    { xmlName: 'TokenList' },
  ],
  tokenScope: [
    'tokenScope',
    optional(lazy(() => tokenScopeSchema)),
    { xmlName: 'TokenScope' },
  ],
});
