/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { TollFreeSettings, tollFreeSettingsSchema } from './tollFreeSettings';

export interface TollFreeSettingsResponse {
  payload?: TollFreeSettings;
}

export const tollFreeSettingsResponseSchema: Schema<TollFreeSettingsResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => tollFreeSettingsSchema)),
      { xmlName: 'TollFreeSettings' },
    ],
  }
);
