/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface TollFreeSettings {
  respOrgException?: boolean;
}

export const tollFreeSettingsSchema: Schema<TollFreeSettings> = object({
  respOrgException: [
    'respOrgException',
    optional(boolean()),
    { xmlName: 'RespOrgException' },
  ],
});
