/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TollFreeWildCharSearchAndOrderType {
  tollFreeWildCardPattern?: string;
  quantity?: number;
}

export const tollFreeWildCharSearchAndOrderTypeSchema: Schema<TollFreeWildCharSearchAndOrderType> = object(
  {
    tollFreeWildCardPattern: [
      'tollFreeWildCardPattern',
      optional(string()),
      { xmlName: 'TollFreeWildCardPattern' },
    ],
    quantity: ['quantity', optional(number()), { xmlName: 'Quantity' }],
  }
);
