/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { TrunkGroup, trunkGroupSchema } from './trunkGroup';

export interface TrunkGroupsPayload {
  trunkGroups?: TrunkGroup[];
}

export const trunkGroupsPayloadSchema: Schema<TrunkGroupsPayload> = object({
  trunkGroups: [
    'trunkGroups',
    optional(array(lazy(() => trunkGroupSchema))),
    { xmlName: 'TrunkGroup' },
  ],
});
