/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TrunkGroup {
  id?: string;
  name?: string;
  status?: string;
  sbcNodeGroup?: string;
  sbcZone?: string;
}

export const trunkGroupSchema: Schema<TrunkGroup> = object({
  id: ['id', optional(string()), { xmlName: 'Id' }],
  name: ['name', optional(string()), { xmlName: 'Name' }],
  status: ['status', optional(string()), { xmlName: 'Status' }],
  sbcNodeGroup: [
    'sbcNodeGroup',
    optional(string()),
    { xmlName: 'SBCNodeGroup' },
  ],
  sbcZone: ['sbcZone', optional(string()), { xmlName: 'SBCZone' }],
});
