/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  TrunkGroupsPayload,
  trunkGroupsPayloadSchema,
} from './trunkGroupsPayload';

export interface TrunkGroupsResponse {
  payload?: TrunkGroupsPayload;
}

export const trunkGroupsResponseSchema: Schema<TrunkGroupsResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => trunkGroupsPayloadSchema)),
    { xmlName: 'TrunkGroups' },
  ],
});
