/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type1Enum
 */
export enum Type1Enum {
  BLOCKED = 'BLOCKED',
  CUSTOMERAPIVALIDATION = 'CUSTOMER_API_VALIDATION',
}

/**
 * Schema for Type1Enum
 */
export const type1EnumSchema: Schema<Type1Enum> = stringEnum(Type1Enum);
