/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface UcTrunkingCloudConfigurationPayload {
  trunks?: string;
}

export const ucTrunkingCloudConfigurationPayloadSchema: Schema<UcTrunkingCloudConfigurationPayload> = object(
  { trunks: ['trunks', optional(string()), { xmlName: 'BiDirectionalTrunks' }] }
);
