/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface UcTrunkingAllocationRule {
  lowerBound?: number;
  ratio?: number;
}

export const ucTrunkingAllocationRuleSchema: Schema<UcTrunkingAllocationRule> = object(
  {
    lowerBound: ['lowerBound', optional(number()), { xmlName: 'LowerBound' }],
    ratio: ['ratio', optional(number()), { xmlName: 'Ratio' }],
  }
);
