/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  UcTrunkingConfigurationPayload,
  ucTrunkingConfigurationPayloadSchema,
} from './ucTrunkingConfigurationPayload';

export interface UcTrunkingConfigurationResponse {
  payload?: UcTrunkingConfigurationPayload;
}

export const ucTrunkingConfigurationResponseSchema: Schema<UcTrunkingConfigurationResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => ucTrunkingConfigurationPayloadSchema)),
      { xmlName: 'UcTrunkingSettings' },
    ],
  }
);
