/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  UcTrunkingCloudConfigurationPayload,
  ucTrunkingCloudConfigurationPayloadSchema,
} from './ucTrunkingCloudConfigurationPayload';

export interface UcTrunkingCloudConfigurationResponse {
  payload?: UcTrunkingCloudConfigurationPayload;
}

export const ucTrunkingCloudConfigurationResponseSchema: Schema<UcTrunkingCloudConfigurationResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => ucTrunkingCloudConfigurationPayloadSchema)),
      { xmlName: 'UcTrunkingCloudSettings' },
    ],
  }
);
