/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { LdapUser, ldapUserSchema } from './ldapUser';

export interface UserAccountsResponse {
  payload?: LdapUser;
}

export const userAccountsResponseSchema: Schema<UserAccountsResponse> = object({
  payload: [
    'payload',
    optional(lazy(() => ldapUserSchema)),
    { xmlName: 'User' },
  ],
});
