/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface UserTelephoneNumbers {
  homePhone?: string;
  cellPhone?: string;
  workPhone?: string;
  otherPhone?: string;
  empty?: boolean;
}

export const userTelephoneNumbersSchema: Schema<UserTelephoneNumbers> = object({
  homePhone: ['homePhone', optional(string()), { xmlName: 'HomePhone' }],
  cellPhone: ['cellPhone', optional(string()), { xmlName: 'CellPhone' }],
  workPhone: ['workPhone', optional(string()), { xmlName: 'WorkPhone' }],
  otherPhone: ['otherPhone', optional(string()), { xmlName: 'OtherPhone' }],
  empty: ['empty', optional(boolean())],
});
