/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { PaginationLinks, paginationLinksSchema } from './paginationLinks';
import {
  UserActivityEvents,
  userActivityEventsSchema,
} from './userActivityEvents';

export interface UserActivityEventLogResponse {
  payload?: UserActivityEvents;
  paginationLinks?: PaginationLinks;
}

export const userActivityEventLogResponseSchema: Schema<UserActivityEventLogResponse> = object(
  {
    payload: [
      'payload',
      optional(lazy(() => userActivityEventsSchema)),
      { xmlName: 'UserEvents' },
    ],
    paginationLinks: [
      'paginationLinks',
      optional(lazy(() => paginationLinksSchema)),
      { xmlName: 'Links' },
    ],
  }
);
