/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import {
  AllowedApiOriginEnum,
  allowedApiOriginEnumSchema,
} from './allowedApiOriginEnum';
import { ScopeEnum, scopeEnumSchema } from './scopeEnum';

export interface UserSettings {
  scope?: string;
  active?: boolean;
  allowedApiOrigin?: string;
  allowedApiOriginEnum?: AllowedApiOriginEnum;
  scopeEnum?: ScopeEnum;
}

export const userSettingsSchema: Schema<UserSettings> = object({
  scope: ['scope', optional(string()), { xmlName: 'Scope' }],
  active: ['active', optional(boolean()), { xmlName: 'Active' }],
  allowedApiOrigin: [
    'allowedApiOrigin',
    optional(string()),
    { xmlName: 'AllowedApiOrigin' },
  ],
  allowedApiOriginEnum: [
    'allowedApiOriginEnum',
    optional(allowedApiOriginEnumSchema),
  ],
  scopeEnum: ['scopeEnum', optional(scopeEnumSchema)],
});
