/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface UserStreetAddress {
  houseNumber?: string;
  streetName?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  empty?: boolean;
}

export const userStreetAddressSchema: Schema<UserStreetAddress> = object({
  houseNumber: ['houseNumber', optional(string()), { xmlName: 'HouseNumber' }],
  streetName: ['streetName', optional(string()), { xmlName: 'StreetName' }],
  city: ['city', optional(string()), { xmlName: 'City' }],
  state: ['state', optional(string()), { xmlName: 'State' }],
  postalCode: ['postalCode', optional(string()), { xmlName: 'PostalCode' }],
  empty: ['empty', optional(boolean())],
});
