/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  UserStreetAddress,
  userStreetAddressSchema,
} from './userStreetAddress';
import {
  UserTelephoneNumbers,
  userTelephoneNumbersSchema,
} from './userTelephoneNumbers';

export interface UserProfile {
  firstName?: string;
  lastName?: string;
  streetAddress?: UserStreetAddress;
  telephoneNumbers?: UserTelephoneNumbers;
  companyName?: string;
}

export const userProfileSchema: Schema<UserProfile> = object({
  firstName: ['firstName', optional(string()), { xmlName: 'FirstName' }],
  lastName: ['lastName', optional(string()), { xmlName: 'LastName' }],
  streetAddress: [
    'streetAddress',
    optional(lazy(() => userStreetAddressSchema)),
    { xmlName: 'StreetAddress' },
  ],
  telephoneNumbers: [
    'telephoneNumbers',
    optional(lazy(() => userTelephoneNumbersSchema)),
    { xmlName: 'TelephoneNumbers' },
  ],
  companyName: ['companyName', optional(string()), { xmlName: 'CompanyName' }],
});
