/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { LdapUser, ldapUserSchema } from './ldapUser';
import {
  UserActivityEvent,
  userActivityEventSchema,
} from './userActivityEvent';

export interface UserActivityEventDetails {
  id?: number;
  version?: number;
  userActivityEvent?: UserActivityEvent;
  userBeforeActivityEvent?: LdapUser;
  userAfterActivityEvent?: LdapUser;
  userBeforeChangeXml?: string;
  userBeforeChangeFromXml?: string;
  userAfterChangeXml?: string;
  userAfterChangeFromXml?: string;
  new?: boolean;
}

export const userActivityEventDetailsSchema: Schema<UserActivityEventDetails> = object(
  {
    id: ['id', optional(number())],
    version: ['version', optional(number())],
    userActivityEvent: [
      'userActivityEvent',
      optional(lazy(() => userActivityEventSchema)),
      { xmlName: 'UserEvent' },
    ],
    userBeforeActivityEvent: [
      'userBeforeActivityEvent',
      optional(lazy(() => ldapUserSchema)),
      { xmlName: 'BeforeChanges' },
    ],
    userAfterActivityEvent: [
      'userAfterActivityEvent',
      optional(lazy(() => ldapUserSchema)),
      { xmlName: 'AfterChanges' },
    ],
    userBeforeChangeXml: ['userBeforeChangeXml', optional(string())],
    userBeforeChangeFromXml: ['userBeforeChangeFromXml', optional(string())],
    userAfterChangeXml: ['userAfterChangeXml', optional(string())],
    userAfterChangeFromXml: ['userAfterChangeFromXml', optional(string())],
    new: ['new', optional(boolean())],
  }
);
