/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UseTypeEnum
 */
export enum UseTypeEnum {
  BUSINESS = 'BUSINESS',
  RESIDENTIAL = 'RESIDENTIAL',
}

/**
 * Schema for UseTypeEnum
 */
export const useTypeEnumSchema: Schema<UseTypeEnum> = stringEnum(UseTypeEnum);
