/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ValidationTypeEnum
 */
export enum ValidationTypeEnum {
  REGEX = 'REGEX',
  LIST = 'LIST',
  MASK = 'MASK',
  GENERIC = 'GENERIC',
}

/**
 * Schema for ValidationTypeEnum
 */
export const validationTypeEnumSchema: Schema<ValidationTypeEnum> = stringEnum(ValidationTypeEnum);
