/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VisibilityEnum
 */
export enum VisibilityEnum {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

/**
 * Schema for VisibilityEnum
 */
export const visibilityEnumSchema: Schema<VisibilityEnum> = stringEnum(VisibilityEnum);
