/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface WirelessInfo {
  id?: number;
  version?: number;
  accountNumber?: string;
  pinNumber?: string;
  new?: boolean;
}

export const wirelessInfoSchema: Schema<WirelessInfo> = object({
  id: ['id', optional(number())],
  version: ['version', optional(number())],
  accountNumber: [
    'accountNumber',
    optional(string()),
    { xmlName: 'AccountNumber' },
  ],
  pinNumber: ['pinNumber', optional(string()), { xmlName: 'PinNumber' }],
  new: ['new', optional(boolean())],
});
