/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface ZIPSearchAndOrderType {
  quantity?: number;
  zip?: string;
}

export const zIPSearchAndOrderTypeSchema: Schema<ZIPSearchAndOrderType> = object(
  {
    quantity: ['quantity', optional(number()), { xmlName: 'Quantity' }],
    zip: ['zip', optional(string()), { xmlName: 'Zip' }],
  }
);
